assets/android.lua
=> fix failed to allocate mcode memory on some android devices

AndroidManifest.xml, assets/android.lua
Unfortunately the screen brightness api is not ready for use now. The brightness is indeed written to system settings but the value is not applied for some reason.
=> Implement io.popen

assets/android.lua
and rename io.stdout to android.stdout to avoid
unnecessary temp file in order to mimic the interface of io.popen
=> Execute with arguments array

.gitmodules
Hope it will improve the poor usability of recent releases.
=> update luajit to the same version as in koreader base

assets/android.lua
This workaround makes a reservation of mmap slots that are hopefully
near the address of `mcode_alloc_at`. Then it unmaps those slots
and lets luajit allocate a large slot for mcode.
=> fix mcode allocation failure on Android

AndroidManifest.xml
Fixes [#1704](https://github.com/koreader/koreader/issues/1704) for the main repo.
=> Workaround for Android not registering the app when there are periods in file patterns

README.md
close https://github.com/koreader/android-luajit-launcher/issues/31
=> add back compress-deflate7 submodule

assets/android.lua, src/org/koreader/launcher/MainActivity.java
Initial commit for Android Fullscreen on/off switch (enable showing android top menu bar).
I'm not sure if those are correct:
"(I)V",
ffi.new('bool'
Help appreciated.
=> [wip] Android Fullscreen switcher

assets/dl.lua
as lua code may request ffi load of library like "libfreetype.so.6"
=> [up] add lib file name without suffix as fallback

src/org/koreader/launcher/MainActivity.java
This is one of the changes to fix issue https://github.com/koreader/koreader/issues/3004.
=> Get screen brightness from Android API

assets/android.lua
Fix to Android fullscreen toggle
=> Android fullscreen fix

assets/android.lua, src/org/koreader/launcher/MainActivity.java
Needed for new viewport setting on koreader 
https://github.com/koreader/koreader/pull/2938
=> Fullscreen status bar height

AndroidManifest.xml, assets/android.lua, src/org/koreader/launcher/MainActivity.java
Bridge/interface to enable,disable, check status Wifi on Android
=> Android Wifi Manager interface

assets/android.lua, assets/install.lua, assets/launcher.lua
In:
* android.lua
* launcher.lua
* install.lua
=> Fix some luacheck warnings

assets/android.lua, src/org/koreader/launcher/MainActivity.java
Allows to keeps screen on https://github.com/koreader/koreader/issues/2748
Please use this as an option/ checkbox in menu, so it won't stop suspending.
=> Android keep screen on 

assets/dl.lua
Fixes https://github.com/koreader/koreader/issues/3126
Thanks to @chrox for testing, see https://github.com/koreader/koreader/issues/3126#issuecomment-335556571.
=> dl.lua: skip system libraries (fix Android 8)

.gitmodules, jni/7zMain.patch, jni/Android.mk
This should fix the x86 Android build on Gitlab.
=> Switch from 6-year-old compress-deflate7 to upstream 7z mirror

.gitmodules
=> [fix] Update 7z URL/commit hash

assets/android.lua, src/org/koreader/launcher/MainActivity.java
Android part of : https://github.com/koreader/koreader/issues/3441
Not tested. Please verify.
@Frenzie FYI
=> Android clipboard interface

assets/android.lua, assets/dl.lua, src/org/koreader/launcher/MainActivity.java
Related to https://github.com/koreader/koreader/issues/4441
1. Add a function to get file path from intent (working from 2.3 to 7.1) - **moved from llapp_main.lua**
2. override current intent with newIntent
3. move a bunch of strings to debug logger
4. fix logging of boolean values
A function to get the file path from 8.0 onwards is missing (intent scheme changed from file to content). I'm not interested in doing this myself since JNI stuff is like Chinese to me.
=> Add logic to launch new files from intent + misc fixes

Makefile
=> [fix] Makefile typo

AndroidManifest.xml
As suggested by @pazos in https://github.com/koreader/koreader/issues/4348#issuecomment-455656058
Fixes https://github.com/koreader/koreader/issues/4348
=> Silence warning on Android 9

build.xml
Related to https://github.com/koreader/koreader/issues/2040
=> disable png optimization

src/org/koreader/device/DeviceInfo.java, src/org/koreader/device/EPDFactory.java
=> add eink support for Inkbook Prime HD

src/org/koreader/device/DeviceInfo.java
add support for inkbook prime, same chipset w/ 6inch 1024x768
=> fix support for inkbook prime hd

assets/android.lua, build.xml, src/org/koreader/device/DeviceInfo.java, src/org/koreader/device/EPDFactory.java
+ overwrite AndroidManifest.xml with previous backup.
+ log time elapsed installing.
=> Add support for eink refreshes on Boyue Likebook Plus

src/org/koreader/device/DeviceInfo.java
=> add support for older energy ereaders

README.md
A follow-up of sorts to #117. I didn't even realize Codacy did Markdown. I just wanted warnings about unused imports and whatnot without having to set up the whole shebang myself.
=> [chore] Fix README codacy issues

src/org/koreader/launcher/MainActivity.java
Which I broke in #104.
Tested on emulator x86 API15
=> unbreak fullscreen toggle in api14-15

src/org/koreader/launcher/Clipboard.java, src/org/koreader/launcher/MainActivity.java, src/org/koreader/launcher/PowerHelper.java, src/org/koreader/launcher/ScreenHelper.java
Remove static context, which is unsafe beecause it can't be garbage collected
Pass application context unless interaction with the screen is needed.
Log catched Java exceptions as errors. 
~~it seems to work, but I need a few days to test.~~
=> fix codacy issues, part 2

.remarkrc
Disable weird indentation default on lists.
See https://github.com/koreader/android-luajit-launcher/pull/121#discussion_r257896837
=> [CI] remarklint config

eink-test/copyEPDControllers.sh, eink-test/res/layout/main.xml, eink-test/src/org/koreader/test/eink/MainActivity.java, src/org/koreader/device/DeviceInfo.java, src/org/koreader/device/EPDFactory.java, src/org/koreader/device/rockchip/RK3368EPDController.java, src/org/koreader/device/rockchip/RK33xxEPDController.java
likebook mimas and probably others.
Related to https://github.com/koreader/koreader/issues/4595
=> [wip]: minimal support for rk33xx

src/org/koreader/device/DeviceInfo.java, src/org/koreader/device/EPDFactory.java
The mars was not reported yet but I gathered the info from the net. It should work as is (same manufacturer, same soc, same everything :))
=> add support for Likebook Mars & Likebook Muses

src/org/koreader/device/DeviceInfo.java
bad copy/paste from mimas :man_facepalming:
=> fix mars & muses device id

assets/android.lua, assets/launcher.lua, jni/android-main.c
- Show assets dir, library dir and external storage dir together.
- Tag main thread logs.
- Store a few more (static) properties on android.prop table.
- Log both assets dir paths on multiuser versions of android (AFAICT every supported version except api14)
=> More logging :d

assets/android.lua, eink-test/copyEPDControllers.sh, eink-test/res/layout/main.xml, eink-test/src/org/koreader/test/eink/MainActivity.java, src/org/koreader/device/DeviceInfo.java, src/org/koreader/device/EPDController.java, src/org/koreader/device/EPDFactory.java, src/org/koreader/device/freescale/NTXEPDController.java, src/org/koreader/device/freescale/NTXNewEPDController.java, src/org/koreader/device/rockchip/RK3026EPDController.java, src/org/koreader/device/rockchip/RK3066EPDController.java, src/org/koreader/device/rockchip/RK30xxEPDController.java, src/org/koreader/device/rockchip/RK3368EPDController.java, src/org/koreader/device/rockchip/RK33xxEPDController.java, src/org/koreader/launcher/MainActivity.java
Tested on Tolino Vision 2, Tolino Shine 3 and Nook Glowlight 3. It should work on other Freescale/NTX devices too.
Updated the einkTest accordly and simplify its interface a little bit (~~don't display device info~~, add a share button instead)
=> Add support for refreshing eink on some Freescale devices

Makefile, gradle.properties, launcher/build.gradle, launcher/src/org/koreader/launcher/Device.java, launcher/src/org/koreader/launcher/MainActivity.java, launcher/src/org/koreader/launcher/NetworkManager.java
Use androidX support libraries instead of legacy. (Requires targetApi 28)
Move network/device methods from MainActivity to their own classes
Fix version code and version name
=> A few things after switching to gradle.

assets/android.lua, launcher/src/org/koreader/launcher/ExternalDict.java, launcher/src/org/koreader/launcher/IntentUtils.java, launcher/src/org/koreader/launcher/MainActivity.java
implemented a few custom intents for some 3rd party apps (Aard2, Quickdic and Colordict) and generic intents for share/send actions.
=> add support for 3rd party dict apps

launcher/src/org/koreader/device/DeviceInfo.java, launcher/src/org/koreader/device/EPDFactory.java
Based on https://github.com/koreader/koreader/issues/4551#issuecomment-507016109 and https://github.com/koreader/koreader/issues/4551#issuecomment-507177518
=> add epd support  for crema 1010p eink device

.remarkrc
At least it fixed the parsing error while running locally.
=> fix .remarkrc

Makefile, README.md, app/AndroidManifest.xml, app/build.gradle, app/src/org/koreader/launcher/BaseActivity.java, app/src/org/koreader/launcher/JNILuaInterface.java, app/src/org/koreader/launcher/helper/ScreenHelper.java, tests/einkTest/src/org/koreader/test/eink/MainActivity.java
=> Some fixes

app/src/org/koreader/launcher/BaseActivity.java
see https://www.mobileread.com/forums/showpost.php?p=3881771&postcount=22
=> workaround for Tolinos on FW10

app/src/org/koreader/launcher/AssetsUtils.java, assets/android.lua, examples/helloWorld/llapp_main.lua, examples/helloWorld/main_loop.lua, examples/helloWorld/utils.lua
Placeholder for some minor things
```
I/KOReader( 1991): Check file in asset module: koreader-v2019.08-55-gec25cea_2019-08-26.7z
I/KOReader( 1991): Found new package revision v2019.08-55-gec25cea_2019-08-26
I/KOReader( 1991): Installing new koreader package to /data/data/org.koreader.launcher/files
I/KOReader( 2013): Check file in asset module: koreader-v2019.08-55-gec25cea_2019-08-26.7z
I/KOReader( 2013): Skip installation for revision v2019.08-55-gec25cea_2019-08-26
```
```
I/KOReader( 2421): Check file in asset module: koreader-v2019.04-250-g9b5a19eb_2019-08-27.zip
I/KOReader( 2421): Found new package revision v2019.04-250-g9b5a19eb_2019-08-27
I/KOReader( 2421): Installing new package to /data/data/org.koreader.launcher/files
I/KOReader( 2443): Check file in asset module: …
```
=> a few minor things

app/src/org/koreader/launcher/AssetsUtils.java, app/src/org/koreader/launcher/BaseActivity.java, app/src/org/koreader/launcher/JNILuaInterface.java, assets/android.lua
See https://github.com/koreader/koreader/pull/5264#issuecomment-526927402
=> avoid the progress dialog unless we're extracting resources from zipfile

app/src/org/koreader/launcher/BaseActivity.java, app/src/org/koreader/launcher/JNILuaInterface.java, app/src/org/koreader/launcher/MainActivity.java, app/src/org/koreader/launcher/helper/BaseHelper.java, app/src/org/koreader/launcher/helper/ClipboardHelper.java, app/src/org/koreader/launcher/helper/NetworkHelper.java, app/src/org/koreader/launcher/helper/PowerHelper.java, app/src/org/koreader/launcher/helper/ScreenHelper.java, assets/android.lua
As they can be used outside activities for doing long term app things.
Switch to in-app brightness.
~~Barely tested,~~ can wait...
=> helpers shouldn't hold a reference to the activity

app/res/drawable/discrete_spinner.xml, app/res/drawable/discrete_spinner_node_a.xml, app/res/drawable/discrete_spinner_node_b.xml, app/src/org/koreader/launcher/BaseActivity.kt
A loading indicator using discrete updates to function better with eInk displays.
Tested down to android 4.4.2
=> eInk friendly spinner

app/AndroidManifest.xml, app/res/drawable/splash_icon.xml, app/res/values/styles.xml, app/src/org/koreader/launcher/BaseActivity.kt, app/src/org/koreader/launcher/JNILuaInterface.kt, app/src/org/koreader/launcher/MainActivity.kt, assets/android.lua
Displays the koreader icon on a white background while the MainActivity loads.
Renders the koreader icon on a white background to the MainActivity Surface once loaded.
=> Show koreader icon while loading

app/src/org/koreader/launcher/JNILuaInterface.kt, app/src/org/koreader/launcher/MainActivity.kt, app/src/org/koreader/launcher/MainApp.kt, assets/android.lua
Improvement over #190 
I tested this on Moto G5S with great results. Probably needs to be tested in a device with a supported freescale e-ink screen and an haptic engine it something like that already exists.
=> haptic feedback support

app/src/org/koreader/launcher/BaseActivity.kt, assets/android.lua
see https://github.com/koreader/koreader/pull/5454#issuecomment-539870395 and https://github.com/koreader/koreader/pull/5454#issuecomment-540055850
=> fix clipboard

app/src/org/koreader/launcher/BaseActivity.kt, app/src/org/koreader/launcher/JNILuaInterface.kt, app/src/org/koreader/launcher/MainApp.kt, assets/android.lua
Related to https://github.com/koreader/koreader/issues/5487
=> external storage: dynamic path based on app reported info

app/src/org/koreader/launcher/EPDFactory.kt
needed to build after #197
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/198)
=> remove old/broken imports

app/src/org/koreader/launcher/DeviceInfo.kt
Related with https://github.com/koreader/koreader/issues/4551
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/202)
=> add support for a couple of Nooks

app/src/org/koreader/launcher/BaseActivity.kt
Fixes #199
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/205)
=> Use freescale driver on CREMA, in spite of being ICS.

app/src/org/koreader/launcher/BaseActivity.kt, app/src/org/koreader/launcher/IntentUtils.kt, app/src/org/koreader/launcher/JNILuaInterface.kt, assets/android.lua
https://github.com/koreader/koreader/issues/5730
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/211)
=> dict lookup: fix NPE

app/src/org/koreader/launcher/BaseActivity.kt, assets/android.lua
Related: https://github.com/koreader/koreader/issues/5731
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/215)
=> catch download exceptions

app/src/org/koreader/launcher/BaseActivity.kt, app/src/org/koreader/launcher/IntentUtils.kt, app/src/org/koreader/launcher/JNILuaInterface.kt, assets/android.lua
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/216)
=> send text to other activities

build.gradle, gradle/wrapper/gradle-wrapper.properties
Related to https://github.com/koreader/koreader/issues/5781
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/219)
=> downgrade gradle plugin + wrapper (partially reverts #217)

app/src/org/koreader/launcher/DeviceInfo.kt, app/src/org/koreader/launcher/EPDFactory.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/222)
=> add likebook ares

app/src/org/koreader/launcher/DeviceInfo.kt, app/src/org/koreader/launcher/EPDFactory.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/223)
=> add Crema Carta+

app/src/org/koreader/launcher/BaseActivity.kt, app/src/org/koreader/launcher/MainActivity.kt, app/src/org/koreader/launcher/device/DeviceInfo.kt, app/src/org/koreader/launcher/device/EPDFactory.kt, app/src/org/koreader/launcher/device/freescale/NTXNewEPDController.kt, app/src/org/koreader/launcher/device/rockchip/RK3026EPDController.kt, app/src/org/koreader/launcher/device/rockchip/RK3368EPDController.kt, app/src/org/koreader/launcher/interfaces/EPDInterface.kt, app/src/org/koreader/launcher/interfaces/JNILuaInterface.kt, app/src/org/koreader/launcher/utils/AssetsUtils.kt, app/src/org/koreader/launcher/utils/FileUtils.kt, app/src/org/koreader/launcher/utils/IntentUtils.kt, app/src/org/koreader/launcher/utils/Logger.kt, app/src/org/koreader/launcher/utils/ScreenUtils.kt, app/src/org/koreader/launcher/utils/SystemSettings.kt
Splits launcher app in packages.
updates LuaJIT to stay in sync with ko-base
It seems to work :p
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/224)
=> Package refactor + LuaJIT bump

app/src/org/koreader/launcher/device/DeviceInfo.kt, app/src/org/koreader/launcher/device/EPDFactory.kt
https://www.mobileread.com/forums/showpost.php?p=3958840&postcount=11
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/226)
=> add support for Boyue/JDRead T65S

app/src/org/koreader/launcher/device/DeviceInfo.kt
It is basically a rebranded Nook.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/229)
=> add mobiscribe

app/src/org/koreader/launcher/MainActivity.kt, app/src/org/koreader/launcher/interfaces/JNILuaInterface.kt, assets/android.lua
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/232)
=> toggle ignore input as a workaround to avoid ANRs on blocking tasks

assets/android.lua
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/233)
=> add option to ignore the back button

app/manifest/base.xml, app/src/org/koreader/launcher/BaseActivity.kt, app/src/org/koreader/launcher/interfaces/JNILuaInterface.kt, assets/android.lua, assets/dl.lua, assets/elf.lua, assets/launcher.lua
Covers the full range of posible orientation for API14+. (Some others were added on API18 but probably they're not interesting enough)
It also fixes a lot of warnings in assets
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/234)
=> orientation support

jni/luajit/koreader-luajit-makefile-tweaks.patch
Oops ^^.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/237)
=> Forgot to update the LuaJIT patch in #236 ;p.

app/src/org/koreader/launcher/BaseActivity.kt, app/src/org/koreader/launcher/EPDTestActivity.kt, app/src/org/koreader/launcher/MainActivity.kt, app/src/org/koreader/launcher/device/DeviceInfo.kt, app/src/org/koreader/launcher/device/EPDFactory.kt, app/src/org/koreader/launcher/device/LightsFactory.kt, app/src/org/koreader/launcher/device/epd/freescale/NTXEPDController.kt, app/src/org/koreader/launcher/device/epd/freescale/NTXNewEPDController.kt, app/src/org/koreader/launcher/device/epd/rockchip/RK3026EPDController.kt, app/src/org/koreader/launcher/device/epd/rockchip/RK30xxEPDController.kt, app/src/org/koreader/launcher/device/epd/rockchip/RK3368EPDController.kt, app/src/org/koreader/launcher/device/epd/rockchip/RK33xxEPDController.kt, app/src/org/koreader/launcher/device/lights/GenericController.kt, app/src/org/koreader/launcher/device/lights/TolinoWarmthController.kt, app/src/org/koreader/launcher/interfaces/JNILuaInterface.kt, app/src/org/koreader/launcher/interfaces/LightInterface.kt, app/src/org/koreader/launcher/utils/ScreenUtils.kt, app/src/org/koreader/launcher/utils/SystemSettings.kt, assets/android.lua, detekt.yml
use a native alertDialog to change brightness (and warmth on supported devices).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/239)
=> light device abstraction and native frontlight dialog

app/src/org/koreader/launcher/utils/FileUtils.kt
https://github.com/koreader/koreader/issues/6459
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/243)
=> catch FileNotFoundException in openFileDescriptor

app/src/org/koreader/launcher/device/DeviceInfo.kt, app/src/org/koreader/launcher/device/LightsFactory.kt, app/src/org/koreader/launcher/device/lights/OnyxWarmthController.kt
When run it crashes with
`E KOReader: [NativeThread]: failed to run script: frontend/ui/widget/frontlightwidget.lua:426: bad argument #1 to 'floor' (number expected, got nil)`
Do I need to add anything to frontend part? I'm pretty sure it everything should be handled already
Pinging @zwim @pazos since you probably have more idea
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/248)
=> Add Onyx Nova 2 frontlight controller

app/build.gradle, app/res/drawable/splash_icon.xml, app/src/org/koreader/launcher/MainActivity.kt
- Fix splash screen
- Crunch adaptative icons
- Simplify contexts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/267)
=> Misc thingies

.gitignore, Makefile, app/res/drawable-v26/splash_icon.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/269)
=> Misc fixes

app/src/org/koreader/launcher/Clipboard.kt, app/src/org/koreader/launcher/Device.kt, app/src/org/koreader/launcher/MainActivity.kt, app/src/org/koreader/launcher/Timeout.kt, app/src/org/koreader/launcher/interfaces/JNILuaInterface.kt, app/src/org/koreader/launcher/utils/ScreenUtils.kt, assets/android.lua
Since we have `JNI:callBooleanMethod`.
~~Untested yet.~~
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/268)
=> int to bool

app/build.gradle, app/src/org/koreader/launcher/MainActivity.kt, app/src/org/koreader/launcher/interfaces/JNILuaInterface.kt, app/src/org/koreader/launcher/utils/ArchiveUtils.kt, assets/android.lua, build.gradle
To fix https://github.com/koreader/koreader/issues/6613
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/270)
=> native unpackArchive

jni/luajit/koreader-luajit-makefile-tweaks.patch
(20201204)
https://github.com/koreader/koreader-base/pull/1256
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/273)
=> Resync LuaJIT w/ KOReader

assets/android.lua
Let's see if that helps with the weird-ass dlopen issues...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/280)
=> Revert most of the recent mcode trickery

app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt, app/src/main/java/org/koreader/launcher/device/EPDFactory.kt
Add support for Likebook P6
Disable HW rotation on Onyx Kon-Tiki
https://github.com/koreader/koreader/issues/4551#issuecomment-748637624
https://github.com/koreader/koreader/issues/7052
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/282)
=> More device ids

app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt
And will never spend a single minute with another Onyx device, unless I buy one myself :cry:
https://github.com/koreader/koreader/issues/7052#issuecomment-753488751
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/286)
=> Revert SW rota for Onyx Kon-Tiki

jni/luajit/koreader-luajit-mcode-debug.patch, jni/luajit/koreader-luajit-mcode-reserve-hack.patch
* Fix pointer arithmetic on !x86/!x64
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/287)
=> Update LuaJIT mcode hack

jni/luajit/koreader-luajit-makefile-tweaks.patch, jni/luajit/koreader-luajit-mcode-debug.patch, jni/luajit/koreader-luajit-mcode-reserve-hack.patch
c.f., https://github.com/koreader/koreader-base/pull/1341
Debugging changes made the mcode patch a tad more annoying, but, eh', it works ;).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/296)
=> Bump LuaJIT

assets/android.lua, build.gradle
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/306)
=> keep track of running state

app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt, app/src/main/java/org/koreader/launcher/device/EPDFactory.kt
From https://github.com/koreader/koreader/issues/4551
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/308)
=> new device defs + update Boyues to match last FW

app/src/main/java/org/koreader/launcher/MainActivity.kt, app/src/main/java/org/koreader/launcher/interfaces/JNILuaInterface.kt, assets/android.lua
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/309)
=> dump logcat to file

app/src/main/java/org/koreader/launcher/MainActivity.kt, app/src/main/java/org/koreader/launcher/utils/IntentUtils.kt
Moved SAF intent logic there
Moved dictLookup logic to MainActivity.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/310)
=> chore: IntentUtils

app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt, app/src/main/java/org/koreader/launcher/device/EPDFactory.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/319)
=> epd: Boyue P78

app/src/main/java/org/koreader/launcher/LuaInterface.kt, app/src/main/java/org/koreader/launcher/MainActivity.kt, app/src/main/java/org/koreader/launcher/device/Device.kt, app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt, assets/android.lua
Utterly broken it is :p
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/320)
=> workaround for Onyx Poke2 nonsense

app/src/main/java/org/koreader/launcher/MainActivity.kt
Fix https://github.com/koreader/koreader/issues/7865
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/321)
=> clipdata: sanitize text

app/src/main/java/org/koreader/launcher/extensions/FileExtensions.kt
Should fix https://github.com/koreader/koreader/issues/7920
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/325)
=> fix symlink on Pre-Lollipop

app/src/main/java/org/koreader/launcher/Assets.kt, app/src/main/java/org/koreader/launcher/EventReceiver.kt, app/src/main/java/org/koreader/launcher/MainActivity.kt, app/src/main/java/org/koreader/launcher/device/epd/qualcomm/QualcommEPDController.kt, app/src/main/java/org/koreader/launcher/device/lights/OnyxC67Controller.kt, app/src/main/java/org/koreader/launcher/extensions/ActivityExtensions.kt, app/src/main/java/org/koreader/launcher/extensions/FileExtensions.kt, app/src/main/java/org/koreader/launcher/extensions/UriExtensions.kt, detekt.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/326)
=> fix codacy warnings

app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt, app/src/main/java/org/koreader/launcher/device/EPDFactory.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/327)
=> add Boyue Lemon Read M1

app/src/main/AndroidManifest.xml, app/src/main/java/org/koreader/launcher/extensions/FileExtensions.kt, build.gradle
reported by new Android Studio version (2020.03 - Artic Fox)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/330)
=> bump dependencies & fix some issues 

app/src/main/java/org/koreader/launcher/MainApp.kt, app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt, app/src/main/java/org/koreader/launcher/device/EPDFactory.kt, app/src/main/java/org/koreader/launcher/device/LightsFactory.kt, jni/android_native_app_glue/android_native_app_glue.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/332)
=> Log callbacks + new device

app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt, app/src/main/java/org/koreader/launcher/device/EPDFactory.kt, assets/android.lua
wip: waiting for confirmation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/333)
=> nabuk regal hd

app/src/main/java/org/koreader/launcher/LuaInterface.kt, app/src/main/java/org/koreader/launcher/MainActivity.kt, app/src/main/java/org/koreader/launcher/device/EPDFactory.kt, app/src/main/java/org/koreader/launcher/device/EPDInterface.kt, app/src/main/java/org/koreader/launcher/device/epd/OldTolinoEPDController.kt, app/src/main/java/org/koreader/launcher/device/epd/OnyxEPDController.kt, app/src/main/java/org/koreader/launcher/device/epd/RK3026EPDController.kt, app/src/main/java/org/koreader/launcher/device/epd/RK3368EPDController.kt, app/src/main/java/org/koreader/launcher/device/epd/TolinoEPDController.kt, app/src/main/java/org/koreader/launcher/device/epd/freescale/NTXEPDController.kt, app/src/main/java/org/koreader/launcher/device/epd/qualcomm/QualcommEPDController.kt, app/src/main/java/org/koreader/launcher/device/epd/rockchip/RK30xxEPDController.kt, app/src/main/java/org/koreader/launcher/device/epd/rockchip/RK33xxEPDController.kt, assets/android.lua
Makes easier to handle outliers. Required for https://github.com/koreader/koreader/issues/4551#issuecomment-931370121.
Untested. Pinging @zwim and @Galunid. Does the app work fine with this PR in?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/341)
=> add waveform constants to drivers

app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt, app/src/main/java/org/koreader/launcher/device/EPDFactory.kt, app/src/main/java/org/koreader/launcher/device/LightsFactory.kt
thanks  to https://github.com/koreader/android-luajit-launcher/pull/341 i no longer need to fiddle with android.lua so i feel no reason not to commit. I tested the patch before on latest master. Everything works, screen refreshes and backlight controls work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/343)
=> added Onyx Darwin 7

app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt, app/src/main/java/org/koreader/launcher/device/EPDFactory.kt, app/src/main/java/org/koreader/launcher/device/LightsFactory.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/345)
=> support for Onyx Nova3 Color and Onyx Nova Air

app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt, app/src/main/java/org/koreader/launcher/device/EPDFactory.kt, app/src/main/java/org/koreader/launcher/device/LightsFactory.kt, app/src/main/java/org/koreader/launcher/device/lights/OnyxWarmthController.kt
reverts #342
fixes https://github.com/koreader/koreader/issues/8584
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/347)
=> revert #342

app/src/main/java/org/koreader/launcher/ApkUpdater.kt, app/src/main/java/org/koreader/launcher/Assets.kt, app/src/main/java/org/koreader/launcher/extensions/ActivityExtensions.kt
and remove them after a succesful update
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/346)
=> store apk updates in private app dir 

app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt, app/src/main/java/org/koreader/launcher/device/EPDFactory.kt, app/src/main/java/org/koreader/launcher/device/LightsFactory.kt
https://github.com/koreader/android-luajit-launcher/pull/349#issuecomment-1016331638
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/352)
=> add nova3, fix note5

app/src/main/java/org/koreader/launcher/LuaInterface.kt, app/src/main/java/org/koreader/launcher/MainActivity.kt, app/src/main/java/org/koreader/launcher/device/Device.kt, app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt, assets/android.lua
To handle epd + color screens properly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/354)
=> Device: add property hasColorScreen

app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt, app/src/main/java/org/koreader/launcher/device/EPDFactory.kt, app/src/main/java/org/koreader/launcher/device/LightsFactory.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/359)
=> onyx note air

app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt, app/src/main/java/org/koreader/launcher/device/EPDFactory.kt, app/src/main/java/org/koreader/launcher/device/LightsFactory.kt
https://github.com/koreader/koreader/issues/8482#issuecomment-1098596614
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/368)
=> Added support for Onyx Faust 3

app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt, app/src/main/java/org/koreader/launcher/device/EPDFactory.kt, app/src/main/java/org/koreader/launcher/device/LightsFactory.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/369)
=> Support for new Onyx devices: Leaf, Note Pro and Poke3

app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt, app/src/main/java/org/koreader/launcher/device/EPDFactory.kt, app/src/main/java/org/koreader/launcher/device/LightsFactory.kt
add onyx magicbook and ireader r6800
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/373)
=> Another device round

app/src/main/java/org/koreader/launcher/TestActivity.kt, app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt, app/src/main/java/org/koreader/launcher/device/EPDFactory.kt, app/src/main/java/org/koreader/launcher/device/LightsFactory.kt, app/src/main/java/org/koreader/launcher/device/lights/OnyxColorController.kt, app/src/main/java/org/koreader/launcher/device/lights/OnyxWarmthController.kt, app/src/main/java/org/koreader/launcher/device/lights/TolinoWarmthController.kt, app/src/main/java/org/koreader/launcher/extensions/FileExtensions.kt
Leave it open for a while.
Reverts iReader  r6800: https://github.com/koreader/koreader/pull/9290#issuecomment-1173543156
Fixes Note Air 2: https://github.com/koreader/koreader/issues/8482#issuecomment-1173591832
Adds Onyx Poke 4: https://github.com/koreader/koreader/issues/8482#issuecomment-1177383798
Adds epd driver for the Sony DPT-RP1: https://github.com/koreader/koreader/issues/8482#issuecomment-1177472515
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/374)
=> Device fixes

examples/helloWorld/main_loop.lua, examples/helloWorld/utils.lua
Fixes https://github.com/koreader/android-luajit-launcher/issues/367
Didn't check if it crashes with the previous ffi def, but `poll` is the way to go.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/378)
=> update standalone example.

app/build.gradle
To be used by F-Droid
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/403)
=> append arch id to versionCode

app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt, app/src/main/java/org/koreader/launcher/device/EPDFactory.kt, app/src/main/java/org/koreader/launcher/device/LightsFactory.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/406)
=> add Onyx Poke 4 lite

app/src/main/java/org/koreader/launcher/MainActivity.kt
works for me on 13
Please test on <= 12
Fixes: koreader/koreader#9446
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/415)
=> android 13 cutout

app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt, app/src/main/java/org/koreader/launcher/device/EPDFactory.kt, app/src/main/java/org/koreader/launcher/device/LightsFactory.kt
Please add support for my device Onyx Boox Darwin 9.
[test.log](https://github.com/koreader/android-luajit-launcher/files/11534562/test.log)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/417)
=> Add Onyx Boox Darwin 9

app/src/main/java/org/koreader/launcher/extensions/FileExtensions.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/418)
=> simplify `FileExtensions.uncompress` implementation

jni/luajit/luajit-revert-b7a8c7c.patch, jni/luajit/mk-luajit.sh
re: https://github.com/koreader/koreader-base/pull/1633
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/423)
=> Unbreak LuaJIT

app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt, app/src/main/java/org/koreader/launcher/device/EPDFactory.kt, app/src/main/java/org/koreader/launcher/device/LightsFactory.kt
Device info:
Brand: onyx
Model: page
Device: boox
Product: boox
Hardware: qcom
E-ink: Onyx/Qualcomm
Backlight: Onyx/Sdk
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/421)
=> Add Onyx Page

jni/luajit/koreader-luajit-mcode-debug.patch, jni/luajit/koreader-luajit-mcode-reserve-hack.patch
c.f., https://github.com/koreader/koreader-base/pull/1648
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/434)
=> Update LuaJIT to 20230830

app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt, app/src/main/java/org/koreader/launcher/device/EPDFactory.kt
Eink: Onyx/Qualcomm
Light: none worked
Device info:
Brand: onyx
Model: palma
Device: boox
Product: boox
Hardware: qcom
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/432)
=> Add Onyx Palma

app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt, app/src/main/java/org/koreader/launcher/device/EPDFactory.kt, app/src/main/java/org/koreader/launcher/device/LightsFactory.kt
Device info:
Brand: onyx
Model: poke5p
Device: poke5p
Product: poke5p
Hardware: qcom
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/437)
=> Support to Onyx Poke5

app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt, app/src/main/java/org/koreader/launcher/device/LightsFactory.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/446)
=> Use Tolino NTX on Tolino Vision 4 to add warmth support

app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt, app/src/main/java/org/koreader/launcher/device/EPDFactory.kt, app/src/main/java/org/koreader/launcher/device/LightsFactory.kt
Device info:
Brand: onyx
Model: nova
Device: nova
Product: nova
Platform: rk3288
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/443)
=> Support for Onyx Nova

app/src/main/java/org/koreader/launcher/device/epd/NookEPDController.kt
Goes with https://github.com/koreader/koreader-base/pull/1716
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/451)
=> Nooks: delay full update

app/src/main/java/org/koreader/launcher/LuaInterface.kt, app/src/main/java/org/koreader/launcher/MainActivity.kt, app/src/main/java/org/koreader/launcher/device/LightsInterface.kt, app/src/main/java/org/koreader/launcher/device/lights/BoyueS62RootController.kt, app/src/main/java/org/koreader/launcher/device/lights/GenericController.kt, app/src/main/java/org/koreader/launcher/device/lights/OnyxC67Controller.kt, app/src/main/java/org/koreader/launcher/device/lights/OnyxColorController.kt, app/src/main/java/org/koreader/launcher/device/lights/OnyxSdkLightsController.kt, app/src/main/java/org/koreader/launcher/device/lights/OnyxWarmthController.kt, app/src/main/java/org/koreader/launcher/device/lights/TolinoNtxController.kt, app/src/main/java/org/koreader/launcher/device/lights/TolinoRootController.kt, assets/android.lua
@pazos 
These are the changes I did (https://github.com/koreader/koreader/pull/8120#issuecomment-1636970460)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/426)
=> Add hasStandaloneWarmth for OnyxWarmthController devices

app/src/main/java/org/koreader/launcher/device/lights/TolinoNtxNoWarmthController.kt
I've found one more worm missed from the bottle ;-)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/464)
=> fix build error

app/src/main/java/org/koreader/launcher/device/LightsFactory.kt, app/src/main/java/org/koreader/launcher/device/lights/OnyxAdbLightsController.kt
https://github.com/koreader/koreader/issues/11723
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/479)
=> Make OnyxAdbLightsController generic for Novaair support

jni/main.c
Issue: https://github.com/koreader/android-luajit-launcher/issues/463
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/469)
=> fix notch reported size on 1st launch after instal

.codacy.yml, README.md
Fix a broken link spotted in #470
Ignore annoying warnings on the README and duplication/complexity warnings on `DeviceInfo`, since the solution it suggests is worse that the code as is.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/488)
=> codacy: fix badge, ignore warnings

app/build.gradle, app/src/main/java/org/koreader/launcher/ApkUpdater.kt, app/src/main/java/org/koreader/launcher/MainActivity.kt, app/src/main/java/org/koreader/launcher/MainApp.kt, app/src/main/java/org/koreader/launcher/device/Device.kt, app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt, app/src/main/java/org/koreader/launcher/device/epd/NGL4EPDController.kt, app/src/main/java/org/koreader/launcher/device/lights/BoyueS62RootController.kt, app/src/main/java/org/koreader/launcher/device/lights/GenericController.kt, app/src/main/java/org/koreader/launcher/device/lights/OnyxAdbLightsController.kt, app/src/main/java/org/koreader/launcher/device/lights/TolinoNtxNoWarmthController.kt, app/src/main/java/org/koreader/launcher/dialog/ToolTip.kt, app/src/main/java/org/koreader/launcher/extensions/ActivityExtensions.kt, app/src/main/java/org/koreader/launcher/extensions/FileExtensions.kt
* Remove support for legacy methods (used by android <= 4.2)
* Fix a few warnings on drivers
* Remove unused definitions
* Idiomatic kotlin
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/425)
=> Remove support for legacy/deprecated methods

app/src/main/java/org/koreader/launcher/device/LightsFactory.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/493)
=> Change Onyx Page to adb driver

.github/workflows/build.yml, jni/luajit/mk-luajit.sh
Cf. https://github.com/koreader/koreader/pull/12285#issuecomment-2267561414
This would also have caught https://github.com/koreader/koreader-base/pull/1897.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/501)
=> ci: add a simple Github Actions workflow

app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/500)
=> Add color support for Mooink Plus 2c

app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt, app/src/main/java/org/koreader/launcher/device/EPDFactory.kt, app/src/main/java/org/koreader/launcher/device/LightsFactory.kt
Commercial name of product: Crema Grande
Android Version: 4.4.2
Light: Tolino Ntx
Display: Freescale/NTX
Manufacturer: iwg
Brand: crema
Model: crema-0710c
Device: ntx_6sl
Product: ntx_6sl
Hardware: e60qn0
Platform: imx6
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/495)
=> Add support for Crema Grande

app/src/main/java/org/koreader/launcher/Assets.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/504)
=> add debug trace when symlinking an asset

app/src/main/java/org/koreader/launcher/MainActivity.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/508)
=> fix debug trace indentation

app/src/main/java/org/koreader/launcher/TestActivity.kt
c.f https://github.com/koreader/koreader/issues/12541
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/515)
=> TestActivity: show key presses

app/src/main/java/org/koreader/launcher/Assets.kt
They seem no longer needed.
Pinging @benoit-pierre?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/518)
=> assets: remove unused workarounds

app/src/main/java/org/koreader/launcher/Assets.kt
Remove unused import.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/527)
=> assets: minor cleanup

app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/528)
=> suppress warnings on DeviceInfo

app/src/main/java/org/koreader/launcher/extensions/ActivityExtensions.kt, assets/android.lua
+ ignore vpn when it's not paired with wifi/cellular or ethernet transport
Fixes #291
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/529)
=> remove unused network types: bluetooth.

app/src/main/java/org/koreader/launcher/device/EPDFactory.kt
Regression from #526.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/530)
=> fix incorrect eink driver for a number of tolino devices

app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt, app/src/main/java/org/koreader/launcher/device/EPDFactory.kt, app/src/main/java/org/koreader/launcher/device/LightsFactory.kt
Device info:
Brand: onyx
Model: livingstone3
Device: livingstone3
Product: livingstone3
Hardware: qcom
Onyx ADB (lights)
Onyx SDK (lights)
Onyx/Qualcomm (E-ink)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/541)
=> Add support for Onyx Boox Livingstone3

app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt, app/src/main/java/org/koreader/launcher/device/EPDFactory.kt, app/src/main/java/org/koreader/launcher/device/LightsFactory.kt
Eink: Onyx/Qualcomm
Light: Onyx ADB
Device info:
Manufacturer: qualcomm
Brand: onyx
Model: palma2
Device: palma2
Product: palma2
Hardware: qcom
Platform: lito
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/543)
=> Add support for Onyx Boox Palma2

app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt, app/src/main/java/org/koreader/launcher/device/EPDFactory.kt, app/src/main/java/org/koreader/launcher/device/LightsFactory.kt
https://github.com/koreader/koreader/issues/8482#issuecomment-2746309093
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/547)
=> add onyx boox poke6 to devices

app/src/main/java/org/koreader/launcher/device/LightsFactory.kt
Reference: https://github.com/koreader/koreader/issues/8482#issuecomment-2914076926
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/560)
=> Add Onyx Boox Go7 and Palma to ADB for improved lighting
