assets/android.lua, assets/elf.lua
There was a bug that when loading `ffi.load("ssl")`
it tried to read "/system/lib/ssl" directory and made dlopen fail.
This patch fixes this by testing if the filename is a regular file.
=> fix loading dynamic library

assets/android.lua
This can be done later with more user customization.
=> revert force allocation of one large mcode

mk-luajit.sh
In the latest NDK, the toolchain version is 4.9
However, this script uses the folder with 4.6, so it cannot find the files.
When adjusted to 4.9, the android release of KOreader builds fine.
=> Adjust for latest NDK

assets/android.lua, build.xml, mk-luajit.sh
/sdcard of my device is not accessible from apps, which may be a bug of my device. But we definitely should use android.os.Environment.getExternalStorage() instead of hardcoded string for data folder.
So this change is to add this function in android-luajit-launcher layer.
One more change in koreader will use this function to replace the hardcoded /sdcard.
This change also contains an update build.xml and mk-luajit.sh to fix several typos.
=> Add android.externalStorage function

AndroidManifest.xml
- based on https://github.com/SufficientlySecure/document-viewer/blob/master/document-viewer/src/main/AndroidManifest.xml
- fixes https://github.com/koreader/koreader/issues/3006 for PDFs (tested using the approach written in the issue; I did not build the app by myself, just changed this file in the .apk)
- I added other mimetypes based on the supported file types as written in https://github.com/koreader/koreader/blob/master/README.md but couldn't test them; you might want to add more
=> adding mimetypes to open more supported files

.travis.yml
To prevent XML well-formedness issues like in 2c40b08.
=> [CI] Travis XML well-formedness check

AndroidManifest.xml, Makefile, mk-luajit.sh
There are different numbers all over the place, but I *think* the code points toward Android 4 (platform-14) as an intended target.
Also, by using `NDKABI=${NDKABI:-14}` we allow for environment variable overrides. It only sets the default of 14 if $NDKABI isn't set. This is in the same spirit as https://github.com/koreader/koreader/pull/3064
=> [fix] Normalize Android build

AndroidManifest.xml, mk-luajit.sh
I think the comment in here misled me. Everything builds under ABI 9 so there's no reason to enforce 14.
=> revert to min 9

AndroidManifest.xml, assets/android.lua, assets/dl.lua, assets/install.lua, jni/Android.mk, src/org/koreader/launcher/MainActivity.java
Xiaomi MIUI ROMs won't load libandroid.so to the global namespace. We have to load the library by ourselves.
=> fix loading libandroid on MIUI ROMs

Makefile, jni/Android.mk, jni/Application.mk, mk-luajit.sh
Can create an x86 packages combined with  https://github.com/koreader/koreader-base/pull/544
References https://github.com/koreader/koreader/issues/1815
You'll need to manually `./mk-luajit.sh clean` in between builds
for different architectures for the moment.
=> [chore] Respond to ANDROID_ARCH environment variable

assets/dl.lua
These lines enabled us to find the issue for Android 8 and will allow for more immediately useful logs in the future.
=> dl.lua: add extra debug output

assets/android.lua, src/org/koreader/launcher/MainActivity.java
in response to https://github.com/koreader/koreader/pull/3396#pullrequestreview-71096493
Commit from phone. 
needs testing
=> [w.i.p.] isWifiEnabled and isFullscreen use JNI:callBooleanMethod

AndroidManifest.xml
Allows for flipping device orientation: holding it upside-down may be more confortable than the default portrait orientation the maker decided for.
References:
https://stackoverflow.com/questions/582185/android-disable-landscape-mode/582585#582585
https://stackoverflow.com/questions/9801580/screen-orientation-and-values-in-manifest-xml/9801725#9801725
https://developer.android.com/guide/topics/manifest/activity-element.html#screen
Got hold of a cheap tablet on which I tried koreader: koreader was stuck to a single portrait orientation (all the other apps were following 180° device rotation). This default orientation was not confortable (thin side, volume keys, warm area are then at the bottom right corner in my right hand).
I first solved it by using in patch.lua some tricks with:
``` …
```
=> Change screenOrientation to sensorPortrait

src/org/koreader/launcher/MainActivity.java
Otherwise the bottom part of the screen where the controls were can remain black. The delay seems to have no positive effects in my various VMs.
Also see https://www.mobileread.com/forums/showpost.php?p=3665118&postcount=160
=> setFullscreenLayout() without delay as well

assets/install.lua
Leftover from https://github.com/koreader/koreader/pull/3723
There's no need to match a specific pattern.
=> [fix] assets/install.lua: be less precise about revision format

AndroidManifest.xml, Makefile, assets/android.lua, jni/android-main.c, mk-luajit.sh, src/org/koreader/launcher/MainActivity.java
It should be possible to build for API 11 (since both clipboard and screenSize work) changing to `<uses-sdk android:minSdkVersion="11" />.`
related to https://github.com/koreader/koreader/issues/4471
added a function to get sdk version from frontend.
setFullscreen should be now easier to understand.
slightly more verbose if requested.
- handle configurationChanges
- provide a method to dump logs to sdcard: we need a permission for that. read logs. It is easy to implement. Just add the permission in AndroidManifest.xml and use `android.execute("logcat KOReader:V *:I -d /sdcard/koreader/koreader.log")
=> bump minimum target to API14, minimum NDK version to 15 and minimum SDK version to 19.

build.xml
It removes some warnings building against JDK8. In theory it supports building with JDK11/10 too, but I didn't test it.
Related to https://github.com/koreader/koreader/issues/4511#issue-403240699 and https://github.com/koreader/koreader/issues/4511#issuecomment-457757843
=> use java target/source 1.6

Makefile
@pazos It seems cleaner to me that way? In any case I'll push it through for the moment to fix the build. (It was a local change I overlooked yesterday.)
=> [fix] Keep all the binaries in ./bin

src/org/koreader/launcher/MainActivity.java, src/org/koreader/launcher/WakeLockHelper.java
STATUSBAR_HIDDEN is used on API<16 only
WAKELOCKS are all deprecated except PARTIAL, as the time of writting they're available on lastest Android version (9).
=> suppress 'safe' deprecations:

.travis.yml, eink-test/copyEPDControllers.sh
To prevent things like this:
```
In platform/android/luajit-launcher/eink-test/copyEPDControllers.sh line 10:
for EPD in "${ROCKCHIP_EPD}"; do
^-- SC2066: Since you double quoted this, it will not word split, and the loop will only run once.
```
=> [chore, CI] Add shellcheck

AndroidManifest.xml, Makefile, build.xml
Related to https://github.com/koreader/koreader/issues/2040
Fixes #105 
In particular with @Frenzie comment:
> So we'd just force-feed the right values into https://github.com/koreader/android-luajit-launcher/blob/8825b5d9d1c9cc11770c4c8acc099a1b60a16022/AndroidManifest.xml#L4-L5 (whether through Ant or by modifying that file dynamically).
Now ant support dynamic versioning with -Dcode and -Dname. Makefile was upgraded to override AndroidManifest.xml values.
For example: 
```Makefile
make ANDROID_NAME=2018.12-100-deadbeef ANDROID_VERSION=100 release
...
BUILD SUCCESSFUL
Total time: 1 second
cp -pv bin/NativeActivity-release-unsigned.apk bin/NativeActivity.apk
'bin/NativeActivity-release-unsigned.apk' -> 'bin/NativeActivity.apk'
application was built, type: release (unsigned), version: …
```
=> set android versionCode and android versionName at buildtime

jni/android-main.c
Related to https://github.com/koreader/koreader/issues/4543
Exit android_main if the application fails trying to load assets, libraries or trying to run a lua file.
This makes possible to start the activity again when requested without having to "force kill" the application manually.
=> exit after crashing, to avoid unknown states

AndroidManifest.xml, src/org/koreader/launcher/MainActivity.java, src/org/koreader/launcher/ScreenHelper.java
Should fix https://github.com/koreader/koreader/issues/4584
I based this on ndk samples (teapots). But the sample is broken (it sets a listener on visibility changes and even then it calls setImmersiveSticky).
This also removes one of the deprecations (if google's code isnt' totally borked). I tested this on emulator 9/4.2. Can't test in 4.0.3 because google efforts to make our life harder (support for sdcard is broken).
=> Layout fixes

assets/android.lua
Fixes https://github.com/koreader/koreader/issues/4586.
=> [fix] Strip quotes from os.execute arguments

assets/android.lua, src/org/koreader/launcher/MainActivity.java
probably android.notification can be repurposed to notify certain error conditions.
As happens with dialogs, we cannot interact with toasts. We can show elements on top of our activity but we can't touch them. We will need a separate activity if we want that (and we won't want that!)
=> [wip]: add basic support for downloads and notifications

Makefile, assets/android.lua, build.xml, res/values/strings.xml, src/org/koreader/launcher/MainActivity.java
So we can check the flavor at runtime and have different behaviour based on that (ie: ota updates)
=> add support for build "flavors"

AndroidManifest.xml
for android 4.0 - 7.1 the application will be shown in the application picker for viewing supported documents
for android 8.0+ the application will be ignored even on supported documents. 
related to https://github.com/koreader/koreader/issues/4441
=> show in the app picker for supported mimetypes **just** if scheme=file.

assets/android.lua, src/org/koreader/launcher/MainActivity.java
Related to https://github.com/koreader/koreader/issues/4821 and https://github.com/koreader/koreader/pull/4822
Tested on a device opening "https://koreader.rocks".
=> open urls in external browser

.gitignore, Makefile, assets/android.lua, build.xml, eink-test/src/org/koreader/test/eink/MainActivity.java, jni/android-main.c, res/values/strings.xml, src/org/koreader/device/DeviceInfo.java, src/org/koreader/device/EPDFactory.java, src/org/koreader/device/rockchip/RK30xxEPDController.java, src/org/koreader/device/rockchip/RK33xxEPDController.java, src/org/koreader/launcher/Clipboard.java, src/org/koreader/launcher/Logger.java, src/org/koreader/launcher/MainActivity.java, src/org/koreader/launcher/PowerHelper.java, src/org/koreader/launcher/ScreenHelper.java
So we are logging everything to "KOReader" or whatever ANDROID_APPNAME used to build the NativeActivity.
Fixes #135 
Fixed eink-test which I broke updating RK33xx driver.
Fixed (again) mars and muses which weren't recognized as eink devices :/
I will write the companion frontend changes later today!
=> set logger name at build time (based on application name)

assets/android.lua, src/org/koreader/device/EPDFactory.java, src/org/koreader/launcher/Logger.java, src/org/koreader/launcher/MainActivity.java, src/org/koreader/launcher/PowerHelper.java
Reason: while adding new stuff to luajit-launcher I need to read a lot of logs. KOReader debug statements (logged with the verbose level) are not relevant here, so having a separate log level comes handy.
This is my proposal: debug statements are not printed in release builds. If you find the need to include (some of) them in release builds I'm ok with that as long as I can still log the relevant launcher stuff with `KOReader:D` without all the noise logged by the frontend.
Pinging @NiLuJe and @poire-z
=> add logd to log luajit-launcher debug strings

koreader-luajit-makefile-tweaks.patch, mk-luajit.sh
A bit of an emergency fix to just get it working ASAP. A patch was added to base LuaJIT in https://github.com/koreader/koreader-base/pull/892, which caused a mismatch and build failures over here. Unfortunately that was hidden by some excessive Android verbosity inadvertently introduced in https://github.com/koreader/koreader-base/pull/888, and on my local instance where I did a sanity check LuaJIT was already compiled…
=> [fix] Add LuaJIT patch to sync with koreader-base

mk-luajit.sh
By making sure *FLAGS is neutral, HOST_*FLAGS are neutral-enough for the
host, and TARGET_*FLAGS are actually the only thing containing target
specific flags (we can use CFLAGS & LDFLAGS from the env, because Makefile.defs now exports those, and it exports the TARGET variants).
(Lua is a bootstrapping build: it first builds minilua, a minimal lua
interpreter, that needs to run on the host machine, so getting the flags
right not to build the host stuff with target stuff is a bit twisty).
(Notably, the LTO patch ensures stuff is linked with the relevant CFLAGS
variant, which is possibly why this flew under the radar before).
=> Fix LuaJIT build after the recent buildsystem tweaks

src/org/koreader/device/EPDFactory.java, src/org/koreader/launcher/MainActivity.java
in order to interact with the epd driver indirectly, via the View class framework, where the epd driver is hooked.
This is part of the solution proposed in https://github.com/koreader/koreader/issues/3517#issuecomment-485347562 to add support for tolinos, but should be compatible with other devices based on the freescale platform.
All credits to @char11, thanks pal! 
Things are working fine on the emulator/phone, but I lack a eink device to test. 
Please @hugleo, @carlinux, @cellaris (or anybody with a **currently supported** eink device) , could you test https://www.dropbox.com/s/froawrgv4jt6h1p/koreader-android-arm-linux-androideabi-debug-v2019.04-52-g7d742e15_2019-04-22.apk?dl=0 and report if eink updates still work?. Also extra points for the output of `adb logcat -c && adb logcat …
=> SurfaceView override.

assets/android.lua, src/org/koreader/device/DeviceInfo.java, src/org/koreader/launcher/MainActivity.java
- enable wakelocks on buggy firmwares ~~and the x86 emulator~~
~~I added the emulator to test the logic myself. Ofc it isn't needed, but shouldn't hurt.~~
Basically: provides a way to check if a device needs wakelocks enabled and the frontend should disallow changing the state on buggy firmware.
- exposes epd platform to frontend
To request updates differently
- better names in DeviceInfo
fixes #125
=> Misc enhancements

assets/android.lua, src/org/koreader/launcher/MainActivity.java, src/org/koreader/launcher/ScreenHelper.java
See https://github.com/koreader/koreader/issues/4794#issuecomment-473446746
most device owners will want to start KOReader in fullscreen. Only people facing issues where the contents don't fit on available screen area will want to disable fullscreen.
This entire PR does almost nothing. All work need to be done on the frontend.
Related to https://github.com/koreader/koreader/issues/4794
=> add fullscreen toggle for jelly bean

launcher/AndroidManifest.xml, launcher/src/org/koreader/launcher/MainActivity.java
Also set resizeableActivity to false to prevent crashes and take android.max_aspect into account. 
This is needed when targetting api24+
Fix #131 
Fixes https://github.com/koreader/koreader/issues/4769
=> Get notch height into account for reporting screen.height (api 28+)

Makefile, eink-test/build.gradle
Related to https://github.com/koreader/virdevenv/pull/40.
It will create new release apks for einkTest using the Makefile. Debug builds will be ignored.
Artifacts are placed in bin/ with name 'einkTest-${abi}.apk'
=> build eink-test for supported abis only, ignore debug builds, copy artifacts to bin/ folder

assets/android.lua, launcher/src/org/koreader/device/DeviceInfo.java, launcher/src/org/koreader/device/EPDController.java, launcher/src/org/koreader/device/EPDFactory.java, launcher/src/org/koreader/device/freescale/NTXEPDController.java, launcher/src/org/koreader/device/rockchip/RK3026EPDController.java, launcher/src/org/koreader/device/rockchip/RK3066EPDController.java, launcher/src/org/koreader/device/rockchip/RK30xxEPDController.java, launcher/src/org/koreader/device/rockchip/RK3368EPDController.java, launcher/src/org/koreader/device/rockchip/RK33xxEPDController.java, launcher/src/org/koreader/launcher/Device.java, launcher/src/org/koreader/launcher/IntentUtils.java, launcher/src/org/koreader/launcher/MainActivity.java, launcher/src/org/koreader/launcher/NetworkManager.java, launcher/src/org/koreader/launcher/PowerHelper.java, launcher/src/org/koreader/launcher/ScreenHelper.java
Until now we relied on android wide settings or use wakelocks to disable the timeout.
This PR adds other timeout options, which are embedded on the activity lifecycle:
- when the app is resumed use a custom timeout , if any, or acquire a new wakelock.
- when the app is paused restore default timeout or release the wakelock.
Since users can modify the screen timeout from android settings we need to update system timeout on resume too.
Some logs to show how this is integrated into the lifecycle of the activity:
```adb logcat
D/KOReader( 3758): timeout callback, focus: false -> using system settings
D/KOReader( 3758): timeout callback, focus: true -> using system settings
```
```adb logcat
D/KOReader( 3758): set timeout for KOReader: 600 seconds
D/KOReader( 3758): timeout callback, focus: …
```
=> Add options to modify screen timeout while the application is running

assets/android.lua, launcher/src/org/koreader/launcher/MainActivity.java
JNI calls cost a little in terms of user experience (<=1ms) but introduce a delay when used in a motion event pool. Is the delay noticeable? YMMV. 
This fixed broken behaviour introduced in #162 and #163: choosing the JNI/Java thingy instead of keeping everything on lua land.
=> avoid the JNI/Java overhead on input events

app/src/org/koreader/launcher/BaseActivity.java, app/src/org/koreader/launcher/JNILuaInterface.java, app/src/org/koreader/launcher/MainActivity.java, assets/android.lua
Related to https://github.com/koreader/koreader/issues/5205 and  https://github.com/koreader/koreader/issues/5206
- destroy native activity if we don't have rw permissions on external storage (shows an untranslatable message to the user because it is better than nothing).
- add functions to check runtime permissions from lua.
- update comments.
=> Some runtime permission fixes

app/src/org/koreader/launcher/MainActivity.java, app/src/org/koreader/launcher/NativeSurfaceView.java
Related to https://github.com/koreader/koreader/issues/5221.
Don't touch NativeActivity surface unless we run on Tolinos or Crema devices.
Our NativeSurfaceView implementation can be tested on the emulator, by replacing "freescale" with "none". 
Both implementations work and behave exactly the same, in terms of quickness, snapiness and memory usage; on the devices I tried:
Nexus4 emulator: apis 17,23,25,28
nox emulator: api 21
moto-g5s: api 27
**Note**: a developer with a Tolino running FW11 will need to check if all of this is really needed. Until then *it works*
=> use NativeSurfaceView *just* on e-ink freescale boards

app/src/org/koreader/launcher/AssetsUtils.java
and fix two possible NullPointerException.
I did test it quickly (I generated almost-empty commits on KOReader,pushed the APK on /sdcard and installed it with Amaze).
=> overwrite files, show resume at the end of extraction

detekt.yml
Hopefully the last change. I dunno why these kind of warnings are not shown using detekt-cli.
=> disable some code style for kotlin

app/src/org/koreader/launcher/BaseActivity.kt, app/src/org/koreader/launcher/JNILuaInterface.kt, app/src/org/koreader/launcher/MainActivity.kt, assets/android.lua
Just because it looks simpler and applies to all android devices. This implementation avoids the jni/lua overhead.
Splash screen gets updated on every surface change as suggested in https://github.com/koreader/android-luajit-launcher/pull/187#issuecomment-536233247.
When the assets are extracted (or skipped if already installed) we disable the flag to avoid splash screen on each resume.
=> move splash screen to BaseActivity

app/AndroidManifest.xml, app/build.gradle, app/src/org/koreader/launcher/BaseActivity.kt, app/src/org/koreader/launcher/JNILuaInterface.kt, app/src/org/koreader/launcher/MainActivity.kt, app/src/org/koreader/launcher/MainApp.kt, app/src/org/koreader/launcher/ScreenUtils.kt, app/src/org/koreader/launcher/SystemSettings.kt, assets/android.lua
~~:cry: do not merge yet.~~
WRITE_SETTINGS !? - feel free to improve it on the future using screenOn and some sort of the autosuspend plugin that disable screenOn after a certain time.
Safer way to keep the screen on, untested on problematic devices, like the Sony RP-1?
=> windowManager instead of wakelocks directly, restore WRITE_SETTINGS for custom timeouts

app/src/org/koreader/launcher/BaseActivity.kt, app/src/org/koreader/launcher/DeviceInfo.kt, app/src/org/koreader/launcher/IntentUtils.kt, app/src/org/koreader/launcher/JNILuaInterface.kt, app/src/org/koreader/launcher/Logger.kt, assets/android.lua
ACTION_SEND, ACTION_SEARCH and ACTION_PROCESS_TEXT when called without an explicit package will be opened with the application picker if there is more than one alternative to open them.
Also fixed some warnings thrown by Android Studio linter.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/200)
=> Generic intents

app/AndroidManifest.xml, app/build.gradle, app/src/org/koreader/launcher/BaseActivity.kt, app/src/org/koreader/launcher/MainActivity.kt, app/src/org/koreader/launcher/MainApp.kt, assets/android.lua
It includes a minor fix to build ok against targetApi 29
Scoped storage won't affect android 10 unless we use targetApi 29. Current targetApi is still untouched, using level 28.
Basically it replaces storage_path on versions where [getExternalStorageDirectory()](https://developer.android.com/reference/android/os/Environment#getExternalStorageDirectory()) is deprecated, with a known path where RW permissions are granted.
From Android 11 onwards everything outside that directory needs to be accesed using SAF.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/201)
=> initial support for scoped storage

app/AndroidManifest.xml
Fix for https://github.com/koreader/koreader/issues/5698
I have the feeling that this flag was already included at some point and I missed it after some refactor.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/206)
=> do not destroy activity on keyboard changes

app/manifest/base.xml, app/src/org/koreader/launcher/FileUtils.kt, app/src/org/koreader/launcher/MainActivity.kt
Tested with Simple Mobile Tools FM, Root Explorer and Solid Explorer.
It could lead to a false positive if the intent.VIEW contains data other than a file (a pipe, a socket). A false positive would start KOReader in the FM (or whatever the user configured) so it shouldn't hurt.
While this workaround still works on scoped storage devices is totally useless because we won't be able to read the file from the resolved path.
Some background in https://www.mobileread.com/forums/showpost.php?p=3932733&postcount=14 and following posts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/208)
=> resolve file paths delivered as content without importing the file

app/src/org/koreader/launcher/BaseActivity.kt, app/src/org/koreader/launcher/MainApp.kt
Related to #213 
Disable annoying warnings. The project can be built against API29+ without problems. Is just that some things won't be available anymore: toggle wifi & read permission on /sdcard or not needed: request media server scan for downloads.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/214)
=> suppress known deprecation warnings

app/build.gradle, app/manifest/base.xml, app/src/org/koreader/launcher/MainApp.kt, assets/android.lua, assets/dl.lua, build.gradle, gradle/wrapper/gradle-wrapper.properties
VM large heap flag isn't needed AFAICT. In the days android was introduced it was hardcoded to 16MB for "normal" apps and a bit more for apps that use the large heap flag. Nowadays most modern devices report the same value with or without the flag: 384MB~.
the large heap flag is useful for activities that load a bunch of java libraries or that have big drawable objects . That's not our case. We run with about 2-3mb of -vm managed- heap usage and almost 0 allocations.
Anyways, I added a function to retrieve that info and log it.
The other changes: move dlopen to their own log tag.
Log policy violations on debug builds
Add leakCanary to debug builds
So, a catch-em-all log will be: `pidcat org.koreader.launcher -t KOReader -t dlopen -t LeakCanary -t StrictMode` while `adb logcat KOReader:* …
=> Disable large heap for managed (java) memory and add some tools to debug builds to detect issues.

app/manifest/base.xml, app/src/org/koreader/launcher/BaseActivity.kt, app/src/org/koreader/launcher/JNILuaInterface.kt, assets/android.lua
Sample solution for https://github.com/koreader/koreader/issues/5787
Send to android wifi settings instead of dealing with wifi state. Update permissions.
Should work on 99'9999% of android devices, but should be tested against corner cases (aka 4.0.? e-ink devices)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/221)
=> replace WifiManager with ConnectivityManager

app/src/org/koreader/launcher/MainActivity.kt
Probably related to our unorthodox way of dealing with content schemes, because the intent gets cleaned automagically on file schemes.
Fixes https://github.com/koreader/koreader/issues/5877
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/225)
=> clear intents onPause() to avoid replaying them onResume()

Makefile
Fdroid only builds for arm and we don't need that,
https://github.com/koreader/koreader/issues/2040
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/227)
=> same versionCode for arm/x86 builds

app/manifest/base.xml
To avoid `Engine thread destroy requested!`
I would say "handle" because we're doing nothing with them. Just telling android we don't need the application destroyed and recreated when the configuration changed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/242)
=> handle all possible configuration changes

app/src/org/koreader/launcher/device/DeviceInfo.kt, app/src/org/koreader/launcher/device/lights/TolinoWarmthController.kt
The Vision 4 and the Epos 2 use the same DEVICE, BRAND and MODEL identifiers.
For accessing the warmth file, both use different files in /sys/class/backlight/
This PR allows changing warmth on both devices.
Internal: `setLastModified` does not work as expected (i.e. it does not throw an exception), therefore it is better to use `canWrite`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/244)
=> add warmth for Tolino Vision 4

app/src/org/koreader/launcher/device/lights/GenericController.kt
Don't use intensity==0 on generic Android, because this will
lead to using system intensity on front light toggle.
I have opened the possibility (for future) to use the system settings if a negative value is given to `setBrightness`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/246)
=> Brightness on Android

app/src/org/koreader/launcher/MainActivity.kt, app/src/org/koreader/launcher/device/lights/GenericController.kt, app/src/org/koreader/launcher/device/lights/TolinoWarmthController.kt, app/src/org/koreader/launcher/interfaces/JNILuaInterface.kt, app/src/org/koreader/launcher/interfaces/LightInterface.kt, assets/android.lua
Check if frontlight is changeable or locked by system settings, on Tolino.
On Generic Android assume frontlight is always changeable.
It was tested on Tolino Epos2, Vision4, a Phone and on the kodev emulator.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/247)
=> Methods to check if frontlight is changeable

app/res/layout/main.xml, app/src/org/koreader/launcher/EPDTestActivity.kt, app/src/org/koreader/launcher/device/DeviceInfo.kt, app/src/org/koreader/launcher/device/EPDFactory.kt, app/src/org/koreader/launcher/device/epd/qualcomm/QualcommEPDController.kt, app/src/org/koreader/launcher/device/epd/qualcomm/QualcommOnyxEPDController.kt
Currently onyx devices rely on system controller, which doesn't work as well as it could with KOReader.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/250)
=> Implement EPD Controller for newer Onyx Boox devices (Qualcomm)

app/src/org/koreader/launcher/Device.kt
It somehow got lost after resolving conflict.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/259)
=> Add missing qualcomm declaration

assets/android.lua
Rationale:
Each time a new epd driver is added we need to tell KOReader which epd modes, waveforms and delays to use. That involved changes in https://github.com/koreader/koreader-base/blob/master/ffi/framebuffer_android.lua.
This PR adds a new function `android.getEinkConstants()` to retrieve these values in framebuffer_android.lua, so hopefully changes there are not needed (or at least will be tiny).
@Galunid  made some valid points in https://github.com/koreader/koreader-base/pull/1221#issuecomment-717258983, about moving these constants to each EPD driver, but IMO they belong to the "lua bridge" as they describe the behaviour expected by the frontend and not the **only valid** way of drive each eink screen.
---
This change is [<img src="https://reviewable.io/review_button.svg" …
=> move eink constants from base

README.md
cf. https://github.com/koreader/android-luajit-launcher/issues/262
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/263)
=> Make explicit ./mk-luajit.sh is intended to be used with NDK r15c

Makefile, app/build.gradle, app/fdroid/org/koreader/launcher/ApkUpdater.kt, app/manifest/base.xml, app/manifest/rocks.xml, app/res/values/strings.xml, app/rocks/org/koreader/launcher/ApkUpdater.kt, app/src/org/koreader/launcher/EPDTestActivity.kt, app/src/org/koreader/launcher/MainApp.kt, app/src/org/koreader/launcher/utils/Permissions.kt, app/src/org/koreader/launcher/utils/ScreenUtils.kt, build.gradle, gradle/wrapper/gradle-wrapper.properties
So Google changed his scoped storage enforcement for Android 11+. It is indeed cool because killing the File API was nosense: https://developer.android.com/training/data-storage/manage-all-files
It is a draft, as it requires changes in the build server and the toolchain:
```diff
diff --git a/toolchain/Makefile b/toolchain/Makefile
index 684b51e..3e12a83 100644
--- a/toolchain/Makefile
+++ b/toolchain/Makefile
@@ -19,7 +19,7 @@ android-sdk:
pushd $(SDK_DIR)/tools/bin && \
yes | ./sdkmanager --update && \
yes | ./sdkmanager --licenses && \
-               ./sdkmanager "platform-tools" "build-tools;28.0.3" "platforms;android-28" "patcher;v4" && \
+               ./sdkmanager "platform-tools" "build-tools;30.0.2" "platforms;android-30" "patcher;v4" && \
popd
rm -f $(SDK_DIR)/$(SDK_TARBALL) …
```
=> bump to API 30

app/src/org/koreader/launcher/MainActivity.kt, app/src/org/koreader/launcher/interfaces/JNILuaInterface.kt, app/src/org/koreader/launcher/utils/FileUtils.kt, assets/android.lua
Based on a hack, but it is the only way to get the path and it is extensively used elsewhere.
It should be reliable enough on 4.4+ and should produce a catched exception on 4.0 - 4.3.
At the same time on 4.0 - 4.3 probably there're no restrictions to move between volumes using our filemanager.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/266)
=> get absolute path of external sdcard

Makefile, app/build.gradle, jni/luajit/mk-luajit.sh
Add a new abi, called arm64-v8a by Google, based on ARMv8a instruction set architecture. This is 64bits, FPU and SIMD/NEON or whatever the hell that means.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/196)
=> add aarch64 support

app/build.gradle, app/manifest/base.xml, app/src/org/koreader/launcher/utils/Permissions.kt, build.gradle
Keeping compileSdk in 30, to repurpose parts of the code, the new docker image and keep updated tools. 
Related to https://github.com/koreader/koreader/issues/6953
We can't bump targetSdk until `sdcv` is replaced by a library.
Refs:
https://developer.android.com/about/versions/10/behavior-changes-10#execute-permission
Somehow this is not enforced on some emulator versions and doesn't apply to custom LineageOS builds which set selinux to permissive. :facepalm: :man_facepalming: :woman_facepalming:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/271)
=> return to target API28

app/src/org/koreader/launcher/utils/ArchiveUtils.kt
Fix for some dicts that have no dir entries.
Ie:
instead of
```
someDict/
someDict/foo
someDict/bar
```
have:
```
someDict/foo
someDict/bar
```
It also adds some robustness in the extraction and an option to delete the container once sucesfully uncompressed. The later is disabled by default to match the behaviour of other platforms.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/274)
=> archiveUtils fixes

assets/android.lua, jni/android-main.c
Because 512K really doesn't work :/.
Also include a stupid hack so that base can detect Android -_-".
----
As the commit log says, I may ultimately try the mmap trick the proper way, but since it requires a shared lib and I'm not at all familiar with all that would entail, not today.
For now, this should just make sure performance doesn't regress because of #278 ;).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/279)
=> Re-tune the mcode hack

Makefile, assets/android.lua, assets/dl.lua, jni/Android.mk, jni/android-main.c, jni/luajit/koreader-luajit-makefile-tweaks.patch, jni/luajit/koreader-luajit-mcode-debug.patch, jni/luajit/koreader-luajit-mcode-reserve-hack.patch, jni/luajit/mk-luajit.sh
Okay, ignore the insane commit history, because this went through a *lot* of experimentation, especially since I found out my old Nexus 5 on 7.1 didn't give a damn about the initial workaround that yielded decent results on Android 10...
Anyway.
* Move to a shared luajit library. This gets rid of the weird hack where the launcher was named libluajit for... reasons (related, ironically, to static linking, and old broken API levels).
* Simplified the dlopen replacement given that fact, and actually implemented the system libs blacklist properly (not that it should be necessary).
* And, as far as the LuaJIT mcode_alloc issues go:
* Make sure the launcher requests a single 512K block right at startup.
* Patch LuaJIT so that:
* Flushing all traces doesn't unmap the mcode area, but instead zero …
=> Tackle mcode_alloc issues once and for all

app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt
Crappy crappy company. Buggy buggy FW.
https://github.com/koreader/koreader/issues/4551#issuecomment-753428909
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/284)
=> Fix Likebook P6 on newer FW

jni/luajit/koreader-luajit-mcode-debug.patch, jni/luajit/koreader-luajit-mcode-reserve-hack.patch
Better comments, make it track mcode_allocarea to make it easier to follow, and fix a corner-case that would never happen on Android ;).
(This makes the patch sane to use on "standard" platforms, with or without the reserve. And testing confirmed that unmapping/remapping the reserve works).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/285)
=> Minor tweaks to the LuaJIT mcode hack

app/src/main/java/org/koreader/launcher/MainActivity.kt, app/src/main/java/org/koreader/launcher/interfaces/JNILuaInterface.kt, app/src/main/java/org/koreader/launcher/utils/ScreenUtils.kt, assets/android.lua
Looks simple enough (he said, hopefully ;p) :).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/288)
=> Fix & enable HW rotation on notched devices on P+

app/src/main/java/org/koreader/launcher/MainActivity.kt, app/src/main/java/org/koreader/launcher/utils/ScreenUtils.kt
Need confirmation in https://github.com/koreader/koreader/issues/7193#issuecomment-766717114
Also: log pixel format on each surface change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/292)
=> Load LuaJIT before the native entry point

app/src/main/java/org/koreader/launcher/utils/ScreenUtils.kt
e.g., my phone defaults to OPAQUE (which translates to something
non-stupid that works ;p. Possibly RGBX_8888).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/295)
=> Add a few likely PixelFormats to ScreenUtils.pixelFormatName

app/src/main/java/org/koreader/launcher/Device.kt, app/src/main/java/org/koreader/launcher/EventReceiver.kt, app/src/main/java/org/koreader/launcher/MainActivity.kt, app/src/main/java/org/koreader/launcher/MainApp.kt
Sorry @zwim, as most intents here were covered by your original PR (ie: separate file for the broadcast receiver class). I just found it confusing on previous iterations but now it makes all the sense in the world (to me :p).
A few changes:
- Be very verbose with the event filter and when a new event is registered/dispatched.
On app launch something like this will be logged:
```
V  [EventReceiver] Filtering 2 events:
V  android.intent.action.ACTION_POWER_CONNECTED
V  android.intent.action.ACTION_POWER_DISCONNECTED
```
- Use a hashmap between android broadcast events/intents and our event codes
That makes easier to watch new events, just asign the map between the intent and the event code in `init` and the new event will be automatically added to the filter and its asigned code pushed to …
=> Broadcast Receiver class

jni/android_native_app_glue/android_native_app_glue.c
This will allow sanely draining them in a single waitForEvent iteration.
Testing the user pipe is a bit tricky, but after switching to wireless adb, I did manage to confirm that it behaved sensibly.
Same for the command pipe (a resume after a task switch was a great testcase for multiple commands in the queue).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/299)
=> Make the CMD & USER pipes NONBLOCK

jni/android_native_app_glue/android_native_app_glue.c
To differentiate them from the pre_exec_cmd ones.
Otherwise, you can get two "APP_CMD_TERM_WINDOW" messages back to back,
which is mildly confusing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/300)
=> Tweak post_cmd_exec debug log messages

app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt, app/src/main/java/org/koreader/launcher/device/LightsFactory.kt, app/src/main/java/org/koreader/launcher/device/lights/OnyxC67Controller.kt
Onyx Boox C67ML doesn't use the Android API for brightness control.
I created a LightsController using sysfs, similar to the Onyx Nova 2's Controller.
Fixes: https://github.com/koreader/koreader/issues/5944, https://github.com/koreader/koreader/issues/2105, https://github.com/koreader/koreader/issues/1651
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/301)
=> Add backlight support for Onyx C67

app/src/main/java/org/koreader/launcher/Assets.kt
A few changes.
1. Instead of extracting the 1st 7z file iterate over the entire assets store and extract them all.
2. APK bundled version isn't part of the 7z name. Now it is stored as a separate text file within the assets module.
3. Instead of complicated logic based on the assets present on the APK we use a for loop and extract everything available based on its type.
For standalone apps based on android-luajit-launcher module the behaviour would be the same. If the APK contains a version.txt then extract only if bundled differs from installed. Else extract on every launch.
See how the inner of the APK looks:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launch …
=> simplify assets extraction

app/build.gradle, app/proguard-rules.pro, app/src/main/AndroidManifest.xml, app/src/main/java/org/koreader/launcher/Assets.kt, app/src/main/java/org/koreader/launcher/EventReceiver.kt, app/src/main/java/org/koreader/launcher/LuaInterface.kt, app/src/main/java/org/koreader/launcher/MainActivity.kt, app/src/main/java/org/koreader/launcher/MainApp.kt, app/src/main/java/org/koreader/launcher/device/Device.kt, app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt, app/src/main/java/org/koreader/launcher/device/EPDFactory.kt, app/src/main/java/org/koreader/launcher/device/EPDInterface.kt, app/src/main/java/org/koreader/launcher/device/LightsFactory.kt, app/src/main/java/org/koreader/launcher/device/LightsInterface.kt, app/src/main/java/org/koreader/launcher/device/epd/freescale/NTXEPDController.kt, app/src/main/java/org/koreader/launcher/device/epd/freescale/NTXNewEPDController.kt, app/src/main/java/org/koreader/launcher/device/epd/qualcomm/QualcommEPDController.kt, app/src/main/java/org/koreader/launcher/device/epd/qualcomm/QualcommOnyxEPDController.kt, app/src/main/java/org/koreader/launcher/device/epd/rockchip/RK3026EPDController.kt, app/src/main/java/org/koreader/launcher/device/epd/rockchip/RK30xxEPDController.kt, app/src/main/java/org/koreader/launcher/device/epd/rockchip/RK3368EPDController.kt, app/src/main/java/org/koreader/launcher/device/epd/rockchip/RK33xxEPDController.kt, app/src/main/java/org/koreader/launcher/device/lights/GenericController.kt, app/src/main/java/org/koreader/launcher/device/lights/OnyxC67Controller.kt, app/src/main/java/org/koreader/launcher/device/lights/OnyxWarmthController.kt, app/src/main/java/org/koreader/launcher/device/lights/TolinoWarmthController.kt, assets/android.lua, assets/dl.lua, assets/launcher.lua, build.gradle
Fairly minor changes in the grand scheme of things :)
Mainly to behave like a "normal" android app: with proguard/R8 rules and JIT/AOT compilation of kotlin classes.
I changed a few other things and removed some useless logs. 
* add proguard rules (don't obfuscate, keep line numbers for debugging stack traces, keep the entire `org.koreader.launcher` package)
* avoid packaging useless metadata into the APK
* refactor classes, finish migration to MultidexApp
* simplify `launcher.lua`
* use different log levels on `dlopen.lua`
* enable AOT compilation of JVM code
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/313)
=> [wip]: refactor + proguard

app/build.gradle, app/proguard-rules.pro, app/src/main/AndroidManifest.xml, app/src/main/java/org/koreader/launcher/CrashReportActivity.kt, app/src/main/java/org/koreader/launcher/EPDTestActivity.kt, app/src/main/java/org/koreader/launcher/LuaInterface.kt, app/src/main/java/org/koreader/launcher/MainActivity.kt, app/src/main/java/org/koreader/launcher/MainApp.kt, app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt, app/src/main/java/org/koreader/launcher/utils/Permissions.kt, app/src/main/res/layout/crash_report.xml, app/src/main/res/layout/epd_test.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml, assets/android.lua, build.gradle, jni/main.c
Add a crash reporter that gets fired after an error in the frontend.
The same crash reporter is also fired in the case of an uncaught exception in the JVM.
The JNI interface is still unsafe. Exceptions raised there will absolutely crash the JVM without any bug report activity.
About signals:  SIGQUIT (used by ANR dialog) won't trigger the crash reporter. The rest of error signals (SIGSEV, SIGILL, SIGBUS...) should do, with the exception of SIGABRT. 
Also: migrate activities to AppCompatActivity and reduce boilerplate using view binding.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/315)
=> Crash reporter

app/src/main/java/org/koreader/launcher/LuaInterface.kt, app/src/main/java/org/koreader/launcher/MainActivity.kt, app/src/main/java/org/koreader/launcher/MainApp.kt, app/src/main/java/org/koreader/launcher/extensions/ActivityExtensions.kt, app/src/main/res/values/strings.xml, assets/android.lua, jni/Android.mk, jni/jni_helper.c, jni/jni_helper.h, jni/main.c
- Block until permissions are granted before launching the LuaJIT vm. 
- Don't raise errors if runtime permissions were rejected (can happen). Just show a toast and finish the activity.
- Annotate all methods called from lua as `@WorkerThread`
- Continue migration to kotlin extensions.
- Reworked mandatory permissions
I refactored a bit the C/JNI code. Probably some stuff in `jni_helper.c` can be abstracted away, but I'm fine as is and it seems to work fine :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/316)
=> Some early init changes

app/src/main/java/org/koreader/launcher/MainActivity.kt, app/src/main/java/org/koreader/launcher/extensions/ActivityExtensions.kt
I found it while playing with https://github.com/koreader/koreader/issues/7837. intent was missing after some refactor and the app just borked in Android11+.
On the bright side now we redirect users to the specific settings for KOReader instead of the full list of app that declare `MANAGE_EXTERNAL_STORAGE` permission.
Merging soon, before the actual bug hits a nightly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/317)
=> quick fix for Android11

app/src/main/java/org/koreader/launcher/LuaInterface.kt, app/src/main/java/org/koreader/launcher/MainActivity.kt, app/src/main/java/org/koreader/launcher/device/Device.kt, app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt, assets/android.lua
Inner changes:
- Renames "bugs" as "quirks" to acommodate new fw/platform oddities.
- Adds a new device property: `hasLights` than can be disabled by device id (I disabled it for the Sony RP1 as it doesn't have frontlight)
Platform changes:
- Disables the light dialog handling for AndroidTV and ChromeOS. They have no effect.
- Disables OTA updates on ChromeOS. APK installation is forbidden unless the device is in Developer mode (aka: rooted) and even there the results aren't reliable. (I can get the apk to start downloading but it never finish it. If I replace the uncomplete download with an OK apk and restart the program it can install the updates fine)
--- …
=> A few platform fixes

app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt, app/src/main/java/org/koreader/launcher/device/EPDFactory.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/348)
=> Add onyx max

app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt, app/src/main/java/org/koreader/launcher/device/EPDFactory.kt, app/src/main/java/org/koreader/launcher/device/LightsFactory.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/349)
=> Add Onyx Note 3 & Onyx Note 5

app/src/main/java/org/koreader/launcher/TestActivity.kt, app/src/main/java/org/koreader/launcher/device/LightsInterface.kt, app/src/main/java/org/koreader/launcher/device/lights/GenericController.kt, app/src/main/java/org/koreader/launcher/device/lights/OnyxC67Controller.kt, app/src/main/java/org/koreader/launcher/device/lights/OnyxWarmthController.kt, app/src/main/java/org/koreader/launcher/device/lights/TolinoWarmthController.kt, app/src/main/java/org/koreader/launcher/dialog/LightDialog.kt, app/src/main/res/layout/test.xml
Don't squash!
1. The test activity now probes the device itself and shows if it is already supported in KOReader (and which drivers it uses)
2. Fixed title not displaying properly on LightDialog. Also added an horizontal line and some margin if the dialog title isn't empty
3. If the title is empty the dialog will look much simpler. That's my suggestion for the frontend. It will look like:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/350)
=> Minor fixes

app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt, app/src/main/java/org/koreader/launcher/device/EPDFactory.kt, app/src/main/java/org/koreader/launcher/device/LightsFactory.kt
Hi, I wanted koreader to run on my Poke Pro so I looked at a previous PR that added "more onyx" support and made the same changes for Poke Pro.
Hope it looks good and can be merged 😊
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/357)
=> Add driver support for onyx poke pro

app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt, app/src/main/java/org/koreader/launcher/device/EPDFactory.kt
This is a device that uses the Onyx/Qualcomm e-ink driver, but has no
backlighting.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/370)
=> Add support for Onyx Note

app/src/main/java/org/koreader/launcher/ApkUpdater.kt, app/src/main/java/org/koreader/launcher/LuaInterface.kt, app/src/main/java/org/koreader/launcher/MainActivity.kt, app/src/main/java/org/koreader/launcher/device/epd/qualcomm/QualcommEPDController.kt, app/src/main/java/org/koreader/launcher/extensions/ActivityExtensions.kt, assets/android.lua, detekt.yml
Intended to fix https://github.com/koreader/koreader/issues/9178
Since I needed to write a new function for generic sendText I implemented @uroybd request at
https://github.com/koreader/koreader/pull/9153#issuecomment-1143857139
Needs a minor change in the frontend:
```diff
diff --git a/frontend/apps/reader/modules/readerhighlight.lua b/frontend/apps/reader/modules/readerhighlight.lua
index 5f439ee6..344bdf12 100644
--- a/frontend/apps/reader/modules/readerhighlight.lua
+++ b/frontend/apps/reader/modules/readerhighlight.lua
@@ -179,7 +179,7 @@ function ReaderHighlight:init()
local text = cleanupSelectedText(_self.selected_text.text)
-- call self:onClose() before calling the android framework
_self:onClose()
-                    Device.doShareText(text)
+ …
```
=> decouple dictionary actions from generic shareText

app/src/main/java/org/koreader/launcher/TestActivity.kt, app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt, app/src/main/java/org/koreader/launcher/device/EPDFactory.kt, app/src/main/java/org/koreader/launcher/device/LightsFactory.kt, app/src/main/java/org/koreader/launcher/device/lights/OnyxSdkLightsController.kt
Follow-up to #342. When classes or methods don't exist, KOReader doesn't crash, addressing koreader/koreader#8584.
Tested on an Onyx Nova Air C. cc/ @bezmi @Galunid
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/372)
=> Add Onyx SDK lights controller, Onyx Note Air2, & Onyx Nova Air C

.codacy.yml
Because with current abstraction it only adds noise.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/384)
=> disable duplication check in device drivers

app/src/main/java/org/koreader/launcher/LuaInterface.kt, app/src/main/java/org/koreader/launcher/MainActivity.kt, app/src/main/java/org/koreader/launcher/device/Device.kt, app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt, assets/android.lua
Same intent as #381 but exporting them all.
It makes possible to have very specific branches to workaround broken aosp devices, like
```lua
if android.prop.is_tolino then
if android.prop.hardware ~= "whatever" or android.prop.model ~= "device" then
-- stuff for all tolino devices except whatever/device
end
end
```
exports manufacturer, brand, device, model, product and hardware as strings and boolean values for `is_tolino` and `is_boyue` as both brands use some non AOSP keycodes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/383)
=> export device properties

app/src/main/java/org/koreader/launcher/TestActivity.kt, app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt, app/src/main/java/org/koreader/launcher/device/Ioctl.kt, app/src/main/java/org/koreader/launcher/device/LightsFactory.kt, app/src/main/java/org/koreader/launcher/device/lights/TolinoNtxController.kt, app/src/main/java/org/koreader/launcher/device/lights/TolinoRootController.kt, app/src/main/java/org/koreader/launcher/device/lights/TolinoVision5WarmthController.kt, app/src/main/java/org/koreader/launcher/device/lights/TolinoWarmthController.kt
This PR adds support in `TolinoWarmthController.kt` to use `/dev/ntx_io` to set the Warmth
fixes #351
~~requires https://github.com/koreader/koreader/pull/9511~~
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/382)
=> Add support for setting Warmth for Tolino with `ntx_io`

.codacy.yml
as they were with web config, missing since https://github.com/koreader/android-luajit-launcher/pull/384
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/385)
=> restore global exclude paths

jni/luajit/koreader-luajit-enable-table_pack.patch, jni/luajit/mk-luajit.sh
c.f., https://github.com/koreader/koreader-base/pull/1535
Note that I left a couple of `{...}` constructs alone in android.lua, because some were then passing the table to `table.concat`, which *will* choke on a nil (and it gets to iterate over it in a packed vararg table).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/388)
=> Build LuaJIT w/ table.pack support

app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt, app/src/main/java/org/koreader/launcher/device/LightsFactory.kt
This PR changes the lights driver on Tolino Shine 3 devices to Tolino ntx to be able to set the warmth through the slider.
Tested on my Tolino Shine 3 device.
This fixes #399
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/400)
=> Use Tolino NTX on Tolino Shine 3 to add warmth support

app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt, app/src/main/java/org/koreader/launcher/device/EPDFactory.kt, app/src/main/java/org/koreader/launcher/device/LightsFactory.kt
I have tested KOReader compatibility on my Boox Note X2 and found that the "Onyx SDK (lights)" and "Onyx/Qualcomm" options worked for me. Since the device info section was printing "notex2" as the model, I edited the code to mimic issue #394. Please note that while I am experienced in systems programming, I am not familiar with Android development. Your help is much appreciated :-)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/402)
=> Add Support for Onyx Boox Note X2

app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt, app/src/main/java/org/koreader/launcher/device/EPDFactory.kt
Boyue Likebook LemonRead S62A
Just the basic place holder.
I've written a wip frontlight controller too. But, although it reads fine, to write the brightness it needs system write so I haven't tested or added it to the pull. Attached here for reference: [BoyueS62Controller.zip](https://github.com/koreader/android-luajit-launcher/files/10683215/BoyueS62Controller.zip)
References: 
1. PhoneStatusBar.java from SystemUI.apk (deodox and decompile with jadx) showing the frontlight logic: [PhoneStatusBar.zip](https://github.com/koreader/android-luajit-launcher/files/10683289/PhoneStatusBar.zip)
It also mentions _/sys/class/backlight/rk28_bl_warm/brightness_ but permissions are required there as well.
2. RK3368Impl.java from Boyue-Launcher.apk (deodox and decompile with jadx) showing mostly the …
=> Add Boyue S62

app/src/main/java/org/koreader/launcher/TestActivity.kt, app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt, app/src/main/java/org/koreader/launcher/device/LightsFactory.kt, app/src/main/java/org/koreader/launcher/device/lights/BoyueS62RootController.kt
requires root.
Notes:
1. This should also work on the [Boyue Likebook Mimas (T103D)](https://www.mobileread.com/forums/showpost.php?p=3890090&postcount=583) and possibly a few other models: https://www.mobileread.com/forums/showthread.php?t=311910&page=39
2. Technically, *boyue_warm_light* is accessible to the shell user (via adb) so it's possible to use shizuku for rootless frontlight. However, since this model is an Android 6 firmware, it will be highly inconvenient as the the user will have run "adb shell sh /sdcard/Android/data/moe.shizuku.privileged.api/start.sh" via the pc with every reboot.
Still, it's something to consider if later Haoqingtech (formerly boyue) models (Meebook P10 Pro, Meebook P78 pro and MeeBook M6 so far...) have similar issues as they're Android 11 based and can …
=> Add Boyue S62 root light controller

Makefile, app/src/main/java/org/koreader/launcher/Assets.kt, app/src/main/java/org/koreader/launcher/MainActivity.kt, app/src/main/java/org/koreader/launcher/device/Ioctl.kt, build.gradle, jni/luajit/mk-luajit.sh
The API level is now encoded in the toolchain executable names, and can be used in place.
Additionally, rework `jni/luajit/mk-luajit.sh` so each architecture has its own build directory (no need to clean when switching architecture). Note: the patches are applied to each build directory, not the original source checkout.
Bump minimum SDK version to 18 in `build.gradle`: the NDK version 23c minimal supported version is 16, but our builds only really work on 18 and above.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/419)
=> update to use NDK 23c

assets/android.lua, assets/dl.lua
Cf. https://github.com/koreader/koreader/issues/10533.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/441)
=> fix native libraries search path

jni/luajit/koreader-luajit-makefile-tweaks.patch, jni/luajit/koreader-luajit-mcode-debug.patch, jni/luajit/koreader-luajit-mcode-reserve-hack.patch
c.f., https://github.com/koreader/koreader-base/pull/1663
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/442)
=> Bump LuaJIT to 20231008

app/src/main/java/org/koreader/launcher/MainActivity.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/439)
=> Reverted cutout and fix rotations

app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt, app/src/main/java/org/koreader/launcher/device/EPDFactory.kt, app/src/main/java/org/koreader/launcher/device/LightsFactory.kt
Commercial name of product: Onyx Boox Note 4
Android Version: 11 (Firmware 3.3.2)
Test lights: Onyx SDK (lights) work
Test E-INK: Qualcomm/Onyx works
Device info:
Brand: onyx
Model: mc_note4
Device: boox
Product: boox
Hardware: qcom
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/454)
=> Onyx boox note 4 support

app/src/main/java/org/koreader/launcher/TestActivity.kt, app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt, app/src/main/java/org/koreader/launcher/device/LightsFactory.kt, app/src/main/java/org/koreader/launcher/device/lights/TolinoNtxNoWarmthController.kt
Closes #455
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/458)
=> Tolino Page 2 support

app/src/main/java/org/koreader/launcher/MainActivity.kt, app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt, app/src/main/java/org/koreader/launcher/device/EPDFactory.kt, app/src/main/java/org/koreader/launcher/device/epd/NGL4EPDController.kt
This commit overrides the [previously closed](https://github.com/koreader/android-luajit-launcher/pull/450) with the following changes
- `NativeSurfaceView` is brought to top in order for Nook Glowlight 4 refresh to work. This change logically affects other controllers that report `needsView`, but the change should be compatible 
- `NGL4EPDController.kt` module was introduced (mostly in the previous PR)  with all registering routines. In this PR made several changes based on the previous tests and discussions. 
The changes were tested on Nook Glowlight 4e (debug compilation to `koreader-android-arm-debug-v2023.10-82-g5d2a44106_2023-12-29.apk`)
- - - …
=> Nook Glowlight 4/4e/4 plus EInk refresh support (full-only)

app/src/main/java/org/koreader/launcher/TestActivity.kt
This modification will allow for any new device without eInk support to test it either with the refresh constant from the Nook Glowlight 4/4e/4 plus series.
The current drawback of the commit (if to say so) is that since the controllers are probably sorted by class names, the Nook GL4 becomes the first in the list and selected (the only direct competitor for sorting might be `Freescale..` but it has the class name `TolinoEPDController` so alphabetically it's after).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/465)
=> Modification to TestActivity.kt adding Nook GL4 support for testing

app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt, app/src/main/java/org/koreader/launcher/device/EPDFactory.kt
These are all OEM variations of the same hardware, which itself originates from the Sony DPT-RP1 design that was licensed to Linfiny.
From https://github.com/koreader/koreader/issues/8482#issuecomment-1986743868
> Commercial name of the product: QuirkLogic Papyr
> Android version: 5.1
> Device has no lights
> Freescale/NXT is the only eink driver that works
> Report:
> [test.log](https://github.com/koreader/koreader/files/14545151/test.log)
I tested this on my QuirkLogic Papyr and it seems to work fine.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/472)
=> Add Linfiny eNote / Avalue ENT-13T1 / QuirkLogic Papyr

app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt, app/src/main/java/org/koreader/launcher/device/EPDFactory.kt
commercial name of product: C64P (Boyue P6 Knockoff) android version: 8.1
driver(s) that work;
Rockchip RK3368
Rockchip RK3026
Other:
None of the light drivers work in the compatibility checker but light works in the app. My device only works in A2 mode.
*Tolino/NTX driver doesnt work.
Device info:
Manufacturer: c64p
Brand: c64p
Model: c64p
Device: c64p
Product: c64p
Platform: rk3326
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/474)
=> Add support for C64P

build.gradle, gradle/wrapper/gradle-wrapper.properties
So Java 17 can be used, the minimum required version to use the most recent Android SDK tools like `sdkmanager`.
The `koandroid` docker image will have to be updated to Focal (20.04), which is good idea anyway as the currently used version reached EOL in May (Bionic: 18.04).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/445)
=> update Gradle to 7.3.3

app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt, app/src/main/java/org/koreader/launcher/device/EPDFactory.kt
Device info:
Manufacturer: haoqing
Brand: haoqing
Model: m6
Device: m6
Product: rk3566_eink
Platform: rk356x
Working EPD Driver: RK3566
Device info:
Manufacturer: haoqing
Brand: haoqing
Model: m7
Device: m7
Product: rk3566_eink
Platform: rk356x
Working EPD Driver: RK3566
Device info:
Manufacturer: rockchip
Brand: rockchip
Model: moaanmix7
Device: rk3566_eink
Product: moaan
Platform: rk356x
Working EPD Driver: RK3566
Device info:
Manufacturer: rockchip
Brand: rockchip
Model: inkpalmplus
Device: rk3566_eink
Product: moaan
Platform: rk356x
Working EPD Driver: RK3566
- - - …
=> Support for a bunch of rockchip devices

app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt, app/src/main/java/org/koreader/launcher/device/EPDFactory.kt
Support [PUBU Pubook](https://www.pubu.com.tw/campaign/ebook/pubook_se.html).
Android version: 11
```
Device info:
Manufacturer: rockchip
Brand: rockchip
Model: pubook
Device: pubook
Product: pubook
Platform: rk356x
```
[test.log](https://github.com/koreader/android-luajit-launcher/files/15289893/test.log)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/482)
=> support PUBU Pubook device

app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt, app/src/main/java/org/koreader/launcher/device/EPDFactory.kt
Device info:
Manufacturer: hyread
Brand: hyread
Model: k06nu
Device: k06nu
Product: rk3566_eink
Platform: rk356x
Working EPD Driver: RK3566
Device info:
Manufacturer: rakuten kobo inc.
Brand: rakutenkobo
Model: tolino vision 6
Device: tolino
Product: tolino
Hardware: sun8iw15p1
Platform: virgo
Working EPD Driver: NGL4
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/484)
=> Support for Hyread Mini 6 and Tolino Vision 6

jni/lzma/un7zip/7zAssetFile.h
Remove unnecessary static function declarations in header.
(Since `7zExtractor.cpp` also includes `7zAssetFile.h` this can result in compilation warnings).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/485)
=> lzma: minor cleanup

Makefile, gradle.properties
- increase JVM heap space
- disable `lintVitalArmRocksRelease` on CI
- enable caching, parallelization and configuration on demand
Locally, starting with no `~/.gradle` directory and pristine `luajit-launcher` checkout, the time spent running `./gradlew …` is:
|                | no daemon & no cache | no daemon & cache | daemon & cache |
-----------------|---------------------:|------------------:|---------------:|
| master         |                2m52s |             1m27s |            48s |
| PR             |                2m56s |               16s |             7s |
| PR (`CI=true`) |                1m44s |               16s |            N/A |
- - - …
=> speedup gradle

app/build.gradle, app/proguard-rules.pro, app/src/main/AndroidManifest.xml, build.gradle, gradle.properties, gradle/wrapper/gradle-wrapper.properties
* Bump gradle
* Bump kotlin sdk
* Specify ndkVersion, as required by current gradle builds.
* R8 no longers needs java1.8, so we don't need desugaring anymore.
* Fixes a few deprecations
Other deps stay as is. Most of them require a bump in the compileSdk to something modern (33-34).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/487)
=> Update gradle & kotlin, drop desugaring

app/src/main/java/org/koreader/launcher/MainActivity.kt, app/src/main/java/org/koreader/launcher/extensions/UriExtensions.kt
Fix for https://github.com/koreader/koreader/issues/9787
**TODO**
- make `dest` dir configurable.
The new behaviour is:
guess the path if the content seems a local file on a readable path.
fallback to copy to `dest` dir
Logs:
* opening content without copy from a guessed file path
```logcat
06-27 01:06:12.490  8662  8684 I MainActivity: New intent: Intent { act=android.intent.action.VIEW dat=content://me.zhanghai.android.files.file_provider/... typ=application/epub+zip flg=0x13000003 cmp=org.koreader.launcher/.MainActivity (has extras) }.action
06-27 01:06:12.491  8662  8684 I UriHandler: Found content, trying to guess if it's a local file on a readable directory
06-27 01:06:12.500  8662  8684 I UriHandler: Guessed path -> /storage/emulated/0/La peste - Albert Camus.epub
```
* opening …
=> import files

app/src/main/java/org/koreader/launcher/device/LightsFactory.kt
Onyx has released new firmware several months ago already. Fix: https://github.com/koreader/koreader/issues/8482#issuecomment-2198002349
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/492)
=> Change Onyx Poke 5 to adb driver

app/src/main/java/org/koreader/launcher/Assets.kt
Fix for https://github.com/koreader/koreader/issues/12098
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/494)
=> prune old assets before unpacking new ones

app/src/main/res/mipmap-anydpi-v26/icon.xml
Closes #409 .
Adds support for android 13 themed icons. 
As the icons were already monochrome, used the current icons as monochrome variants.
Tested by building and installing on Samsung S21 FE.
Currently only enabled for release builds so as to still differentiate release and debug builds but can also enable to debug build if you would like.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/496)
=> Add support for Android 13 themed icons

app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt, app/src/main/java/org/koreader/launcher/device/EPDFactory.kt, app/src/main/java/org/koreader/launcher/device/LightsFactory.kt
Tolino Epos 3
Android 8.1.0
Eink driver: Nook gl4
Light driver: found none
Device info:
Manufacturer: rakuten kobo inc.
Brand: rakutenkobo
Model: tolino epos 3
Device: tolino
Product: tolino
Hardware: sun8iw15p1
Platform: virgo
Device info:
Manufacturer: unknown
Brand: allwinner
Model: mooink plus 2c
Device: e70p54_android_cfa
Product: e70p54_android_cfa
Hardware: sun8iw15p1
Platform: virgo
Working EPD Driver: NGL4
Nook GlowLight 4
Android 8.1.4
Eink driver: Nook GL4
Light driver: Tolino Root
Device info:
Manufacturer: barnesandnoble
Brand: nook
Model: bnrv1100
Device: e60p54_android
Product: e60p54_android
Hardware: sun8iw15p1
Platform: virgo
Working EPD Driver: Nook GL4
Working Frontlight Driver: Tolino Root
None of the other drivers function at all, but Tolino Root can adjust …
=> Add support for a bunch of devices

assets/dl.lua
Support multi-parts versions, like `libcrypto.so.1.1`.
Necessary for https://github.com/koreader/koreader/pull/12285.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/503)
=> dlopen: fix handling of versioned libraries

jni/luajit/Android.mk, jni/main.c
Add support for using an already compiled LuaJIT.
Necessary for https://github.com/koreader/koreader/pull/12285.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/502)
=> out of tree luajit

app/build.gradle, gradle.properties
This allow for out-of-tree builds (when combined with `--project-cache-dir` and `--project-cache-dir`).
Necessary for https://github.com/koreader/koreader/pull/12285.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/505)
=> gradle: support changing the location of the assets / libraries

assets/android.lua
- update & fix `pthread_cond_t` / `pthread_mutex_t` declarations: correct layout for 64bits
- fix `ANativeActivity` declaration: add missing `obbPath` field (since Android 3 [HoneyComb])
- cleanup, reduce differences with NDK headers
No real impact that I could see:
- no `android_app` structure creation in Lua code, no access "below" the `android_app.config` field (before the "private" fields, including the `pthread_cond_t` / `pthread_mutex_t` one)
- no `ANativeActivity` structure creation in Lua code, missing field was last
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/506)
=> update FFI C declarations

app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt, app/src/main/java/org/koreader/launcher/device/EPDFactory.kt
Onyx Boox Go 10.3
Android: 12
no lights
E-INK: Onyx/Qualcomm (works, screen refreshes)
Device info:
Manufacturer: qualcomm
Brand: onyx
Model: go103
Device: go103
Product: go103
Hardware: qcom
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/509)
=> Onyx Boox Go 10.3 support

assets/dl.lua
Prerequisite for https://github.com/koreader/koreader/pull/12545.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/511)
=> dlopen: fix `dl.open` on absolute path

app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt, app/src/main/java/org/koreader/launcher/device/LightsFactory.kt
Manufacturer: rakuten kobo inc
Brand: rakutenkobo
Model: tolino
Device: ntx_6sl
Product: ntx_6sl
Hardware: e70q20
Platform: imx6
Friendly name:
[test.log](https://github.com/user-attachments/files/17102791/test.log)
Tolino Epos 1
Android 4.4
Tolino Ntx, Freescale/NTX
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/513)
=> Tolino Epos 1 warmth lights support

app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt, app/src/main/java/org/koreader/launcher/device/EPDFactory.kt
Reason: new eink model support
commercial name of product: P101 (Boyue P101)
android version: 8.1
driver(s) that work:
- Rockchip RK3368
- Rockchip RK3026
Device info:
Manufacturer: boyue
Brand: boyue
Model: likebook-p101
Device: p101
Product: p101
Platform: rk3326
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/522)
=> Add support for boyue P101

app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt, app/src/main/java/org/koreader/launcher/device/EPDFactory.kt, app/src/main/java/org/koreader/launcher/device/LightsFactory.kt
Tolino Epos 2
Device info:
Manufacturer: rakuten kobo inc.
Brand: rakutenkobo
Model: tolino
Device: ntx_6sl
Product: ntx_6sl
Hardware: e80k00
Platform: imx6
test.log
Lights: tolino/ntx
Also adds Tolino Epos 1 to EPD driver
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/521)
=> Tolino Epos 2 support

assets/android.lua
Just forward the whole command to `sh -c`, so there's no need to muck around with escaping, and all KOReader's use-cases are supported (redirection, multiple commands, etc…).
Cf. https://github.com/koreader/koreader/pull/12375#issuecomment-2297862418, https://github.com/koreader/koreader/pull/12384 & https://github.com/koreader/koreader/issues/12613#issuecomment-2400879766.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/524)
=> fix `os.execute` implementation

app/src/main/java/org/koreader/launcher/MainActivity.kt, app/src/main/java/org/koreader/launcher/device/Device.kt, app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt, app/src/main/java/org/koreader/launcher/device/EPDFactory.kt, app/src/main/java/org/koreader/launcher/device/LightsFactory.kt, assets/android.lua
Reduce duplication to make it easier to maintain.
Fix the following issues:
- possible problem with `EINK` value on `TOLINO_EPOS3` devices (since both `TOLINO` and `TOLINO_EPOS3` booleans would be set)
- `EINK` was never set to `EinkDevice.TOLINO_VISION6`, but checked in `device/EPDFactory.kt`
- same with `HANVON_960` & `HYREAD_MINI6`
- `LIGHTS` was never set to `LightsDevice.ONYX_NOTE_PRO`, but checked in `device/LightsFactory.kt`
Still not fixed:
~- `LIGTS` could be set to `LightsDevice.ONYX_PALMA`, but was never checked in `device/LightsFactory.kt`~
Also address https://github.com/koreader/android-luajit-launcher/pull/483#issuecomment-2452608471, will conflict with #525.
- - - …
=> rework DeviceInfo.kt

app/src/main/java/org/koreader/launcher/device/LightsFactory.kt
fix https://github.com/koreader/koreader/issues/8482#issuecomment-2500443034
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/531)
=> fix Tolino Epos 2 to the correct light controller

app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt, app/src/main/java/org/koreader/launcher/device/EPDFactory.kt
inkBook Focus 7,8"
Device info:
Manufacturer: rockchip
Brand: rockchip
Model: focus
Device: px30_eink
Product: r07801
Platform: rk3326
Android 8.1
Frontlight: all from list doesnt work
E-ink drivers: Rockchip RK3026 (works)
inkBook Focus Plus 7,8" (Carta 1300)
Device info:
Manufacturer: rockchip
Brand: rockchip
Model: focus plus
Device: rk3566_eink
Product: r07802
Platform: rk356
Android 8.1
Frontlight: none works
E-ink drivers: Rockchip RK3566 (refreshes screen in test, no option to adjust refresh rate in main KoReader menu)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/537)
=> Add suport for some InkBook Focus devices

app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt, app/src/main/java/org/koreader/launcher/device/EPDFactory.kt
Reason: new
commercial name of product: Onyx Boox Note Max
android version: 13
driver(s) that work: E-ink: Onyx/Qualcomm (it has no frontlight)
Manufacturer: qualcomm
Brand: onyx
Model: notemax
Device: notemax
Product: notemax
Hardware: qcom
Platform: msmnile
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/542)
=> Add support for Onyx Boox Note Max

app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt, app/src/main/java/org/koreader/launcher/device/EPDFactory.kt, app/src/main/java/org/koreader/launcher/device/LightsFactory.kt
Onyx Boox Galileo 2 - maybe similar to Onyx Boox Page? Reason: new
commercial name of product: Onyx Boox Galileo 2
android version: 11
driver(s) that work: Onyx ADB (lights), Onyx/Qualcomm (E-ink) Manufacturer: onyx
Brand: onyx
Model: galileo2
Device: boox
Product: boox
Hardware: qcom
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/544)
=> Add support for Onyx Boox Galileo 2

app/src/main/AndroidManifest.xml
Or any app that states `android.intent.category.BROWSABLE` on their intents.
Restricted to `file` and `content` schemes from any host.
Also added a filter by extension, in case the sending app is nuts (I never needed it here but I see it is commonly used)
Also added markdown to the list.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/546)
=> handle uris from browsers

app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt, app/src/main/java/org/koreader/launcher/device/EPDFactory.kt, app/src/main/java/org/koreader/launcher/device/LightsFactory.kt
Hi,
first time i'm doing this, hope is all correct.
Reason:  new
commercial name of product: Boox Note Air4 C
android version: 13 
driver(s) that work:
Lights: Onyx ADB (lights) 
E-ink: Onyx/Qualcomm
[test.log](https://github.com/user-attachments/files/20079576/test.log)
Device info:
Manufacturer: qualcomm
Brand: onyx
Model: noteair4c
Device: noteair4c
Product: noteair4c
Hardware: qcom
Platform: lito
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/551)
=> add noteair4c

app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt, app/src/main/java/org/koreader/launcher/device/EPDFactory.kt, app/src/main/java/org/koreader/launcher/device/LightsFactory.kt
add ONYX_GO6 device entry and detection
```
Device info:
Brand: onyx
Model: go6
Device: boox
Product: boox
Hardware: qcom
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/553)
=> Add Boox Go6 support

app/build.gradle, app/src/main/java/org/koreader/launcher/LuaInterface.kt, app/src/main/java/org/koreader/launcher/MainActivity.kt, app/src/main/java/org/koreader/launcher/extensions/FileExtensions.kt, assets/android.lua, build.gradle
Not needed anymore.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/557)
=> drop untar implementation

app/build.gradle
The deflated version of `koreader.7z` is 5920 bytes bigger!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/559)
=> do not compress 7z files in APK

app/build.gradle
```
Unable to strip the following libraries, packaging them as they are:
libc++_shared.so, libioctl.so, libkoreader-monolibtic.so,
libluajit-launcher.so, libluajit.so, libsdcv.so.
```
Those have already been stripped by the main project build system, but add back the `ndkPath` build setting to make gradle happy.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/558)
=> fix gradle warning

jni/7z/unarchive.c, jni/CMakeLists.txt, jni/ioctl/ioctl.c
To make sure we don't pull in some C++ that would break the ODR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/561)
=> JNI: always use the C interface

app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt, app/src/main/java/org/koreader/launcher/device/EPDFactory.kt, app/src/main/java/org/koreader/launcher/device/LightsFactory.kt
Removed Boox Go7 from EDP driver, and Added Support for Hisense Touch Lite
Reason: new
Commercial name of product: Hisense Touch Lite
Android version: 11
Device info:
Manufacturer: hisense
Brand: hisense
Model: hitv205n
Device: hitv205n
Product: hitv205n
Hardware: qcom
light control works with Tolino driver, but warmth doesn't work.
no e-ink driver works.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/android-luajit-launcher/562)
=> Remove Boox Go7 from EDP driver and add support for Hisense Touch Lite
